/*main title*/
	WINDOW_ID(MT_LOGODLG),
	WINDOW_ID(MT_LOGINDLG),
	WINDOW_ID(MT_BIDLG),
	WINDOW_ID(MT_COPYDLG),
	WINDOW_ID(MT_OKBTN),
	WINDOW_ID(MT_CANCELBTN),
	WINDOW_ID(MT_IDEDITBOX),
	WINDOW_ID(MT_PWDEDITBOX),
	WINDOW_ID(MT_ENDBTN),
	WINDOW_ID(MT_OPTIONBTN),			
	WINDOW_ID(MT_ADDACCOUNTBTN),		// 10
	WINDOW_ID(MT_MAINTITLEDLG),

	// 080111 LYW --- WindowIDs : 보안 비밀번호 입력 창 추가.
	WINDOW_ID(MT_SECURITYPW), 


	// dynamic
	WINDOW_ID(MT_DYNAMICDLG),
	WINDOW_ID(MT_DYNAMICPWDEDITBOX),
	WINDOW_ID(MT_DYNAMICOKBTN),
	WINDOW_ID(MT_DYNAMICEXITBTN),
	WINDOW_ID(MT_STC_DYNAMICID),
	WINDOW_ID(MT_STC_COORD),
	WINDOW_ID(MT_STC_COORD_MAT),

/*char select*/
	WINDOW_ID(CS_CHAR1PUSHBTN),			
	WINDOW_ID(CS_CHAR2PUSHBTN),			// 20
	WINDOW_ID(CS_CHAR3PUSHBTN),
	WINDOW_ID(CS_CHAR4PUSHBTN),
	WINDOW_ID(CS_CHAR1NAMESTATIC),
	WINDOW_ID(CS_CHAR2NAMESTATIC),
	WINDOW_ID(CS_CHAR3NAMESTATIC),
	WINDOW_ID(CS_CHAR4NAMESTATIC),
	WINDOW_ID(CS_CHAR1LEVELSTATIC),

	WINDOW_ID(CS_CHAR2LEVELSTATIC),
	WINDOW_ID(CS_CHAR3LEVELSTATIC),
	WINDOW_ID(CS_CHAR4LEVELSTATIC),		// 30
	WINDOW_ID(CS_CHAR1LOCSTATIC),
	WINDOW_ID(CS_CHAR2LOCSTATIC),
	WINDOW_ID(CS_CHAR3LOCSTATIC),
	WINDOW_ID(CS_CHAR4LOCSTATIC),
	WINDOW_ID(CS_CHARSELECTBTN),
	WINDOW_ID(CS_CHARCREATEBTN),
	WINDOW_ID(CS_CHARDELETEBTN),

	WINDOW_ID(CS_CHARCANCELBTN),		
	WINDOW_ID(CS_CHARSELECTDLG),
	WINDOW_ID(CSID_CharSelectInfoDlg1),	// 40
	WINDOW_ID(CSID_CharSelectInfoDlg2),
	WINDOW_ID(CSID_CharSelectInfoDlg3),
	WINDOW_ID(CSID_CharSelectInfoDlg4),
	WINDOW_ID(CSID_CharLevel1),
	WINDOW_ID(CSID_CharLevel2),
	WINDOW_ID(CSID_CharLevel3),
	WINDOW_ID(CSID_CharLevel4),

	WINDOW_ID(CSID_CharName1),
	WINDOW_ID(CSID_CharName2),
	WINDOW_ID(CSID_CharName3),			// 50
	WINDOW_ID(CSID_CharName4),
	WINDOW_ID(MT_FIRSTCHOSEBTN),
	WINDOW_ID(MT_SECONDCHOSEBTN),
	WINDOW_ID(MT_THIRDCHOSEBTN),
	WINDOW_ID(MT_FOURTHCHOSEBTN),
	WINDOW_ID(MT_FIFTHCHOSEBTN),
	WINDOW_ID(CSID_MessageBox),
	WINDOW_ID(CSID_MessageTxt),	

	// 061215 LYW --- Add window id for character select part.
	WINDOW_ID(CSID_BTN_CREATE), 
	WINDOW_ID(CSID_BTN_DELETE), 
	WINDOW_ID(CSID_BTN_LOGOUT), 
	WINDOW_ID(CSID_BTN_CHANGESERVER), 

	// 061212 LYW --- Add window id for character information.
	WINDOW_ID(CP_PROFILEDLG), 
	WINDOW_ID(CP_CHARNAME),
	WINDOW_ID(CP_LEVEL), 
	WINDOW_ID(CP_CLASS), 
	WINDOW_ID(CP_RACIAL), 
	WINDOW_ID(CP_STARTPOINT), 
	WINDOW_ID(CP_GUILDNAME), 

	// 061218 LYW --- Add window id for interface CertificateDlg.
	WINDOW_ID(CTF_DLG), 
	WINDOW_ID(CTF_BTN_OK), 
	WINDOW_ID(CTF_BTN_CANCEL), 
	WINDOW_ID(CTF_ST_RANNUM), 
	WINDOW_ID(CTF_EB_EDITBOX), 
	WINDOW_ID(CTF_TA_TEXT), 
	// 070117 LYW --- Add window id for title.
	WINDOW_ID( CTF_ST_TEXT ), 
/*AE¡¤¨￢AI ¡iefA¡E  */

/**/
	WINDOW_ID(CMID_MessageBox),
	WINDOW_ID(CMID_MessageTxt),
	WINDOW_ID(CMID_NONableName),		// 60
	WINDOW_ID(CMID_SUCCESSMakeChar),
	WINDOW_ID(CMID_FAILMakeChar),
/*char make*/
/*
	WINDOW_ID(CMID_IDEDITBOX),
	WINDOW_ID(CMID_OverlapCheck),

	WINDOW_ID(CMID_JobType),
	WINDOW_ID(CMID_SexType),
	WINDOW_ID(CMID_ClothType),

	WINDOW_ID(CMID_HairType),
	WINDOW_ID(CMID_FaceType),
	WINDOW_ID(CMID_BootType),
	WINDOW_ID(CMID_WeaponType),
	WINDOW_ID(CMID_StartArea),
	WINDOW_ID(CMID_CharMake),
	WINDOW_ID(CMID_CharCancel),

	WINDOW_ID(CMID_PJobType),	//?
	WINDOW_ID(CMID_PSexType),
	WINDOW_ID(CMID_PBodyType),	


	WINDOW_ID(CMID_PStartArea),
	WINDOW_ID(CMID_ManFaceType),
	WINDOW_ID(CMID_WomanFaceType),
	WINDOW_ID(CMID_ManHairType),
	WINDOW_ID(CMID_WomanHairType),
	WINDOW_ID(CMID_Height),
	WINDOW_ID(CMID_Width),
	*/
	// 061217 LYW --- Delete this code.
	/*
	WINDOW_ID(CMID_AttribType),
	WINDOW_ID(CMID_SexType),
	WINDOW_ID(CMID_ManHairType),
	WINDOW_ID(CMID_WomanHairType),
	WINDOW_ID(CMID_ManFaceType),
	WINDOW_ID(CMID_WomanFaceType),
	WINDOW_ID(CMID_ClothType),
	WINDOW_ID(CMID_BootType),			// 70
	WINDOW_ID(CMID_WeaponType),
	
	WINDOW_ID(CMID_IDEDITBOX),
	WINDOW_ID(CMID_OverlapCheck),
	WINDOW_ID(CMID_CharMake),
	WINDOW_ID(CMID_CharCancel),
	WINDOW_ID(CMID_Height),
	WINDOW_ID(CMID_Width),
	
	WINDOW_ID(CMID_WeaponLeft),
	WINDOW_ID(CMID_WeaponRight),
	WINDOW_ID(CMID_BootLeft),			// 80
	WINDOW_ID(CMID_BootRight),
	WINDOW_ID(CMID_ClothLeft),
	WINDOW_ID(CMID_ClothRight),
	WINDOW_ID(CMID_FaceLeft),
	WINDOW_ID(CMID_FaceRight),
	WINDOW_ID(CMID_HairLeft),
	WINDOW_ID(CMID_HairRight),
	WINDOW_ID(CMID_SexLeft),
	WINDOW_ID(CMID_SexRight),
	WINDOW_ID(CMID_AttribLeft),			// 90
	WINDOW_ID(CMID_AttribRight),
	*/

	// 061215 LYW --- Add new window id for creation character part.
	WINDOW_ID(CM_MAKEDLG), 
	WINDOW_ID(CM_PB_HUMAN), 
	WINDOW_ID(CM_PB_ELF), 
	WINDOW_ID(CM_PB_FIGHTER), 
	WINDOW_ID(CM_PB_MAGE), 
	WINDOW_ID(CM_PB_ROGUE), 
	WINDOW_ID(CM_PB_MAN), 
	WINDOW_ID(CM_PB_WOMAN), 
	WINDOW_ID(CM_ST_MFACE), 
	WINDOW_ID(CM_ST_MHAIR), 
	WINDOW_ID(CM_ST_WMFACE), 
	WINDOW_ID(CM_ST_WMHAIR), 
	WINDOW_ID(CM_ST_EMFACE), 
	WINDOW_ID(CM_ST_EMHAIR), 
	WINDOW_ID(CM_ST_EWMFACE), 
	WINDOW_ID(CM_ST_EWMHAIR),
	WINDOW_ID(CM_SPB_FACE_LEFT), 
	WINDOW_ID(CM_SPB_FACE_RIGHT), 
	WINDOW_ID(CM_SPB_HAIR_LEFT), 
	WINDOW_ID(CM_SPB_HAIR_RIGHT), 
	WINDOW_ID(CM_BTN_CANCEL), 
	WINDOW_ID(CM_BTN_MAKE), 
	WINDOW_ID(CM_TA_RACIAL), 
	WINDOW_ID(CM_TA_CLASS), 
	WINDOW_ID(CM_IDEDITBOX),

	// 061218 LYW --- Add static id for alphawindow id.
	WINDOW_ID(CM_ALPHAWINDOW),
	// 061227 LYW --- Add static id for racial and class.
	WINDOW_ID(CM_ST_RACIAL), 
	WINDOW_ID(CM_ST_CLASS), 



/*Aⓒø￠￢?A¡E*/
	WINDOW_ID(CI_CHARDLG),
	WINDOW_ID(CI_MUNPAMARK),
	WINDOW_ID(CI_CHARMUNPA),
	WINDOW_ID(CI_CHARJIKWE), 
	WINDOW_ID(CI_CHARFAME),

	WINDOW_ID(CI_CHARBADFAME),
	WINDOW_ID(CI_CHARNAME), 
//	WINDOW_ID(CI_CHARSTAGE), 
	WINDOW_ID(CI_CHARSTR),			// 100
	WINDOW_ID(CI_CHARWIS), 
	WINDOW_ID(CI_CHARDEX), 
	WINDOW_ID(CI_CHARVIT), 

	// 070111 LYW --- Add window id for new controls.
	WINDOW_ID(CI_CHARINT), 

	WINDOW_ID(CI_CHARLEVEL),
	WINDOW_ID(CI_CHAREXPPERCENT),
	WINDOW_ID(CI_CHARPOINT),
	WINDOW_ID(CI_CHARJOB),

	WINDOW_ID(CI_CHARATTACK), 
	WINDOW_ID(CI_LONGATTACK), 	
	WINDOW_ID(CI_CHARDEFENSE),			// 110
	WINDOW_ID(CI_CHARKYEONGKONG),
	WINDOW_ID(CI_CHARMOVE),
	WINDOW_ID(CI_CHARLIFE),
	WINDOW_ID(CI_CHARMANA),

	WINDOW_ID(CI_CHARHWA),
	WINDOW_ID(CI_CHARSU),
	WINDOW_ID(CI_CHARMOK),	
	WINDOW_ID(CI_CHARKUM),
	WINDOW_ID(CI_CHARTO),

	WINDOW_ID(CI_SPCHARNAME),			// 120
	WINDOW_ID(CI_CRITICAL),
	WINDOW_ID(CI_DISTANCE),
	WINDOW_ID(CI_HOSINDEFENSE),
	WINDOW_ID(CI_EXPPOINTGUAGE),
	WINDOW_ID(CI_STR_POINT),
	WINDOW_ID(CI_WIS_POINT),
	WINDOW_ID(CI_DEX_POINT),
	WINDOW_ID(CI_VIT_POINT),
	// 070111 LYW --- Add window id for new controls.
	WINDOW_ID(CI_INT_POINT), 
	// 070111 LYW --- Delete these id cus not use.
	/*
	WINDOW_ID(CI_STR_POINT2),
	WINDOW_ID(CI_WIS_POINT2),		// 130
	WINDOW_ID(CI_DEX_POINT2),
	WINDOW_ID(CI_VIT_POINT2),
	*/
	WINDOW_ID(CI_DEFENCE_HWA),
	WINDOW_ID(CI_DEFENCE_SU),
	WINDOW_ID(CI_DEFENCE_MOK),
	WINDOW_ID(CI_DEFENCE_KUM),
	WINDOW_ID(CI_DEFENCE_TO),

	// 06. 02. 내정보창 팁보기 추가 - 이영준
	WINDOW_ID(CI_BESTTIP),

	// 070111 LYW --- Add ids for new controls.
	WINDOW_ID( CI_CLOSEBTN ),
	WINDOW_ID(CI_CLASSTREEBTN ),
	WINDOW_ID(CI_TREEBGIMG), 
	WINDOW_ID(CI_TREEMARK), 
	WINDOW_ID(CI_TREETITLE), 
	WINDOW_ID(CI_SUB_ITEMS1), 
	WINDOW_ID(CI_SUB_ITEMS2), 
	WINDOW_ID(CI_SUB_ITEMS3), 
	WINDOW_ID(CI_SUB_ITEMS4), 
	WINDOW_ID(CI_SUB_ITEMS5), 
	WINDOW_ID(CI_CLASS1_STATIC), 
	WINDOW_ID(CI_CLASS2_STATIC), 
	WINDOW_ID(CI_CLASS3_STATIC1),
	WINDOW_ID(CI_CLASS3_STATIC2), 
	WINDOW_ID(CI_CLASS4_STATIC), 
	WINDOW_ID(CI_CLASS5_STATIC1), 
	WINDOW_ID(CI_CLASS5_STATIC2), 
	WINDOW_ID(CI_CLASS5_STATIC3), 
	WINDOW_ID(CI_CLASS5_STATIC4), 

	// 070112 LYW --- Add window ids for character image.
	WINDOW_ID( CI_CHAR_IMAGE0 ), 
	WINDOW_ID( CI_CHAR_IMAGE1 ), 
	WINDOW_ID( CI_CHAR_IMAGE2 ), 
	WINDOW_ID( CI_CHAR_IMAGE3 ), 

	// 070113 LYW --- Add window ids for controls of character information dialog.
	WINDOW_ID( CI_BGSTATIC_0 ),
	WINDOW_ID( CI_BGSTATIC_1 ),
	WINDOW_ID( CI_BGSTATIC_2 ),
	WINDOW_ID( CI_BGSTATIC_3 ),
	WINDOW_ID( CI_BGSTATIC_4 ),
	WINDOW_ID( CI_BGSTATIC_5 ),
	WINDOW_ID( CI_CIRCLE_IMAGE_0 ),
	WINDOW_ID( CI_CIRCLE_IMAGE_1 ),
	WINDOW_ID( CI_CIRCLE_IMAGE_2 ),
	WINDOW_ID( CI_CIRCLE_IMAGE_3 ),
	WINDOW_ID( CI_CIRCLE_IMAGE_4 ),
	WINDOW_ID( CI_CIRCLE_IMAGE_5 ),
	WINDOW_ID( CI_CIRCLE_IMAGE_6 ),
	WINDOW_ID( CI_CIRCLE_IMAGE_7 ),
	WINDOW_ID( CI_CIRCLE_IMAGE_8 ),
	WINDOW_ID( CI_RESISTANCE_IMAGE0 ),
	WINDOW_ID( CI_RESISTANCE_IMAGE1 ),
	WINDOW_ID( CI_RESISTANCE_IMAGE2 ),
	WINDOW_ID( CI_RESISTANCE_IMAGE3 ),
	WINDOW_ID( CI_RESISTANCE_IMAGE4 ),
	WINDOW_ID( CI_RESISTANCE_IMAGE5 ),
	WINDOW_ID( CI_LOCKED_TEXT0 ), 
	WINDOW_ID( CI_LOCKED_TEXT1 ), 
	WINDOW_ID( CI_LOCKED_TEXT2 ), 
	WINDOW_ID( CI_LOCKED_TEXT3 ), 
	WINDOW_ID( CI_LOCKED_TEXT4 ), 
	WINDOW_ID( CI_LOCKED_TEXT5 ), 
	WINDOW_ID( CI_LOCKED_TEXT6 ), 
	WINDOW_ID( CI_LOCKED_TEXT7 ), 
	WINDOW_ID( CI_LOCKED_TEXT8 ), 
	WINDOW_ID( CI_LOCKED_TEXT9 ), 
	WINDOW_ID( CI_LOCKED_TEXT10 ), 
	WINDOW_ID( CI_LOCKED_TEXT11 ), 
	WINDOW_ID( CI_LOCKED_TEXT12 ), 
	WINDOW_ID( CI_LOCKED_TEXT13 ), 
	WINDOW_ID( CI_LOCKED_TEXT14 ), 
	WINDOW_ID( CI_LOCKED_TEXT15 ), 
	WINDOW_ID( CI_LOCKED_TEXT16 ), 
	WINDOW_ID( CI_LOCKED_TEXT17 ), 
	WINDOW_ID( CI_LOCKED_TEXT18 ), 
	WINDOW_ID( CI_LOCKED_TEXT19 ), 
	WINDOW_ID( CI_LOCKED_TEXT20 ), 
	WINDOW_ID( CI_LOCKED_TEXT21 ), 
	WINDOW_ID( CI_LOCKED_TEXT22 ), 
	WINDOW_ID( CI_LOCKED_TEXT23 ), 
	WINDOW_ID( CI_LOCKED_TEXT24 ), 
	WINDOW_ID( CI_LOCKED_TEXT25 ), 
	WINDOW_ID( CI_LOCKED_TEXT26 ), 
	WINDOW_ID( CI_LOCKED_TEXT27 ), 
	WINDOW_ID( CI_LOCKED_TEXT28 ), 
	WINDOW_ID( CI_LOCKED_TEXT29 ), 
	WINDOW_ID( CI_LOCKED_TEXT30 ), 
	WINDOW_ID( CI_LOCKED_TEXT31 ), 
	WINDOW_ID( CI_LOCKED_TEXT32 ), 
	WINDOW_ID( CI_CHANGED_TEXT0 ), 
	WINDOW_ID( CI_CHANGED_TEXT1 ), 
	WINDOW_ID( CI_CHANGED_TEXT2 ), 
	WINDOW_ID( CI_CHANGED_TEXT3 ), 
	WINDOW_ID( CI_CHANGED_TEXT4 ), 
	WINDOW_ID( CI_CHANGED_TEXT5 ), 
	WINDOW_ID( CI_CHANGED_TEXT6 ), 
	WINDOW_ID( CI_CHANGED_TEXT7 ), 
	WINDOW_ID( CI_CHANGED_TEXT8 ), 
	WINDOW_ID( CI_CHANGED_TEXT9 ), 
	WINDOW_ID( CI_CHANGED_TEXT10 ), 
	WINDOW_ID( CI_CHANGED_TEXT11 ), 
	WINDOW_ID( CI_CHANGED_TEXT12 ), 
	WINDOW_ID( CI_CHANGED_TEXT13 ), 
	WINDOW_ID( CI_CHANGED_TEXT14 ), 
	WINDOW_ID( CI_CHANGED_TEXT15 ), 
	WINDOW_ID( CI_CHANGED_TEXT16 ), 
	WINDOW_ID( CI_CHANGED_TEXT17 ), 
	WINDOW_ID( CI_CHANGED_TEXT18 ), 
	WINDOW_ID( CI_CHANGED_TEXT19 ), 
	WINDOW_ID( CI_CHANGED_TEXT20 ), 
	WINDOW_ID( CI_CHANGED_TEXT21 ), 
	WINDOW_ID( CI_CHANGED_TEXT22 ), 
	WINDOW_ID( CI_CHANGED_TEXT23 ), 
	WINDOW_ID( CI_CHANGED_TEXT24 ), 
	WINDOW_ID( CI_CHANGED_TEXT25 ), 
	WINDOW_ID( CI_CHANGED_TEXT26 ), 
	WINDOW_ID( CI_CHANGED_TEXT27 ), 
	WINDOW_ID( CI_CHANGED_TEXT28 ), 
	WINDOW_ID( CI_STATUS_BTN_0 ), 
	WINDOW_ID( CI_STATUS_BTN_1 ), 
	WINDOW_ID( CI_STATUS_BTN_2 ), 
	WINDOW_ID( CI_STATUS_BTN_3 ), 
	WINDOW_ID( CI_STATUS_BTN_4 ), 

	// 070416 LYW --- WindowIDs : Add window id for print racial to character dialog.
	WINDOW_ID( CI_RACIAL ),

	// 070503 LYW --- WindowIDs : Add window id for setting family name.
	WINDOW_ID( CI_FAMILYNAME ), 


	WINDOW_ID(TIPBROWSER_DLG),
	WINDOW_ID(TB_STATE_PUSHUP1),
	WINDOW_ID(TB_STATE_PUSHUP2),
	WINDOW_ID(TB_STATE_PUSHUP3),
	WINDOW_ID(TB_STATE_PUSHUP4),
	WINDOW_ID(TB_STATE_PO),
	WINDOW_ID(TB_STATE_AG),
	WINDOW_ID(TB_STATE_HE),
	WINDOW_ID(TB_STATE_MA),
	WINDOW_ID(TB_CANCELBTN),
	
/*ⓒo¡i¡ÆⓒªA¡E22*/
	WINDOW_ID(MGI_SKILLSURYUNDLG),
		WINDOW_ID(MGI_SKILLBTN),
		WINDOW_ID(MGI_SURYUNBTN),		// 140

		WINDOW_ID(MGI_SHEET1),	

			WINDOW_ID(MGI_SKILL_PUSHUP1),
			WINDOW_ID(MGI_SKILL_PUSHUP2),
			WINDOW_ID(MGI_JINBUB_PUSHUP3),

			WINDOW_ID(MGI_SKILL1_GRID1),
			WINDOW_ID(MGI_SKILL1_GRID2),
			WINDOW_ID(MGI_JINBUB_GRID),

			WINDOW_ID(MGI_SKILLJINBUB_EXP_GUAGE),
			WINDOW_ID(MGI_SKILLJINBUB_EXP_STATIC),
			WINDOW_ID(MGI_SKILLJINBUB_WEAR),		// 150			
			WINDOW_ID(MGI_SKILLJINBUB_NAME_STATIC),
			WINDOW_ID(MGI_SKILLJINBUB_LEVEL_STATIC),
			
		WINDOW_ID(MGI_SHEET2),
			WINDOW_ID(MGI_SURYUN_PUSHUP1),
			WINDOW_ID(MGI_SURYUN_PUSHUP2),
			WINDOW_ID(MGI_SURYUN_PUSHUP3),
			WINDOW_ID(MGI_SURYUN_PUSHUP4),
			WINDOW_ID(MGI_SURYUN_PUSHUP5),
			WINDOW_ID(MGI_SURYUN1_GRID),
			WINDOW_ID(MGI_SURYUN2_GRID),
			WINDOW_ID(MGI_SURYUN3_GRID),	// 160	

			WINDOW_ID(MGI_SURYUN4_GRID),
			WINDOW_ID(MGI_SURYUN5_GRID),
			WINDOW_ID(MGI_NEEDSURYUN_EXP_STATIC),	//@￠?a¡¾￠￢¨uo¡¤AA￠®
			WINDOW_ID(MGI_SURYUN_EXP_STATIC),	//@¨uo¡¤AA￠®
			WINDOW_ID(MGI_SURYUN_BTN),	//@¨uo¡¤A
			WINDOW_ID(MGI_SKPOINTREDIST_BTN),
/*	
		WINDOW_ID(MGI_SKILLDLG),
	
		WINDOW_ID(MGI_SKILL_WEAR),
		WINDOW_ID(MGI_SKILL_GRID),
		WINDOW_ID(MGI_SKILL_NAME_STATIC),
		WINDOW_ID(MGI_SKILL_LEVEL_STATIC),
		WINDOW_ID(MGI_SKILL_EXP_STATIC),
		WINDOW_ID(MGI_SKILL_EXP_GUAGE),
	
		WINDOW_ID(MGI_JINBUB_WEAR),
		WINDOW_ID(MGI_JINBUB_GRID),
		WINDOW_ID(MGI_JINBUB_NAME_STATIC),
		WINDOW_ID(MGI_JINBUB_LEVEL_STATIC),
		WINDOW_ID(MGI_JINBUB_EXP_STATIC),
		WINDOW_ID(MGI_JINBUB_EXP_GUAGE),
	
		WINDOW_ID(MGI_SIMBUB_WEAR),
		WINDOW_ID(MGI_SIMBUB_GRID),
		WINDOW_ID(MGI_SIMBUB_NAME_STATIC),
		WINDOW_ID(MGI_SIMBUB_LEVEL_STATIC),
		WINDOW_ID(MGI_SIMBUB_EXP_STATIC),
		WINDOW_ID(MGI_SIMBUB_EXP_GUAGE),*/
	

/*￠￢¨­AIAIAI¨¡aAI¨o¨￢10*/
	WINDOW_ID(MI_CHARBTN), 
	WINDOW_ID(MI_EXCHANGEBTN), 
	WINDOW_ID(MI_INVENTORYBTN), 
//	WINDOW_ID(MI_SKILLBTN), 
	WINDOW_ID(MI_SKILLBTN),			// 170
	WINDOW_ID(MI_PARTYBTN),		

	WINDOW_ID(MI_MAINDLG), 
	WINDOW_ID(MI_BTN_SIZE),
	WINDOW_ID(MI_STC_TAIL),

	WINDOW_ID(MI_CHATEDITBOX),
	WINDOW_ID(MI_HEROGUAGE),
	WINDOW_ID(MI_OTHERGUAGE),

/*AI¨￢¡IAa￠￢￠c*/
	WINDOW_ID(IN_INVENTORYDLG),
	WINDOW_ID(IN_WEAREDDLG),
	WINDOW_ID(IN_TABBTN1),			// 180
	WINDOW_ID(IN_TABBTN2),
	WINDOW_ID(IN_TABBTN3),
	WINDOW_ID(IN_TABBTN4),
	/*WINDOW_ID(IN_SHOPITEMBTN),*/

	WINDOW_ID(IN_TABDLG1),
	WINDOW_ID(IN_TABDLG2),
	WINDOW_ID(IN_TABDLG3),
	WINDOW_ID(IN_TABDLG4),
	WINDOW_ID(IN_CREATESTREETSTALL),
	WINDOW_ID(IN_MONEYEDIT),		// 190
	//WINDOW_ID(IN_SHOPITEMGRID),

	// 070323 LYW --- WindowIDs : Add window id for inventory background.
	WINDOW_ID(IN_BACKGROUND1), // Human man
	WINDOW_ID(IN_BACKGROUND2), // Human weman
	WINDOW_ID(IN_BACKGROUND3), // Elf man
	WINDOW_ID(IN_BACKGROUND4), // Elf weman

/*A￠´¨¡AA¡E*/
// 061204 LYW --- Delete Preexistence Chatting Dialog.
	/*
	WINDOW_ID(CTI_DLG),
	WINDOW_ID(CTI_BTN_WHOLE),
	WINDOW_ID(CTI_BTN_PARTY),
	WINDOW_ID(CTI_BTN_MUNPA),
	WINDOW_ID(CTI_BTN_ALLMUNPA),
	WINDOW_ID(CTI_BTN_WORLD),
	WINDOW_ID(CTI_BTN_ALLWORLD1),

	WINDOW_ID(CTI_SHEET1), 
	WINDOW_ID(CTI_SHEET2),			// 200
	WINDOW_ID(CTI_SHEET3),
	WINDOW_ID(CTI_SHEET4),
	WINDOW_ID(CTI_SHEET5),
	WINDOW_ID(CTI_BTN_TALLER),
	WINDOW_ID(CTI_BTN_SMALLER),
	WINDOW_ID(CTI_BTN_OPTION),
	*/

	/// 061130 LYW --- Add Window Id For Chatting Dialog.
	WINDOW_ID( CHATTING_DLG ), 
	WINDOW_ID( CHATTING_BG_NORMAL ), 
	WINDOW_ID( CHATTING_BG_EXTENDED_UP ), 
	WINDOW_ID( CHATTING_BG_EXTENDED_MIDDLE1 ), 
	WINDOW_ID( CHATTING_BG_EXTENDED_MIDDLE2 ), 
	WINDOW_ID( CHATTING_BG_EXTENDED_DOWN ), 
	WINDOW_ID( CHATTING_BG_SCROLLBAR ), 
	WINDOW_ID( CHATTING_LIST_WHOLE ), 
	WINDOW_ID( CHATTING_LIST_PARTY ), 
	WINDOW_ID( CHATTING_LIST_FAMILY ), 
	WINDOW_ID( CHATTING_LIST_GUILD ), 
	WINDOW_ID( CHATTING_LIST_ALLIANCE ), 
	WINDOW_ID( CHATTING_LIST_TRADE ), 
	WINDOW_ID( CHATTING_LIST_SYSTEM ),
	WINDOW_ID( CHATTING_BTN_TALLER ), 
	WINDOW_ID( CHATTING_BTN_WHOLE ),				// Choice Button For Select Chatting List.
	WINDOW_ID( CHATTING_BTN_PARTY ), 
	WINDOW_ID( CHATTING_BTN_FAMILY ), 
	WINDOW_ID( CHATTING_BTN_GUILD ), 
	WINDOW_ID( CHATTING_BTN_ALLIANCE ), 
	WINDOW_ID( CHATTING_BTN_TRADE ), 
	WINDOW_ID( CHATTING_BTN_SYSTEM ), 
	WINDOW_ID( CHATTING_ST_EMBTN_BACK ),  
	WINDOW_ID( CHATTING_BTN_EMCALL ),				// Call Emoticon Icon Button.
	WINDOW_ID( CHATTING_BTN_SORRY ),
	WINDOW_ID( CHATTING_BTN_DELIGHT ),
	WINDOW_ID( CHATTING_BTN_SORROW ),
	WINDOW_ID( CHATTING_BTN_HAHA ),
	WINDOW_ID( CHATTING_BTN_SOLUTATION ),
	WINDOW_ID( CHATTING_BTN_HELP ),
	WINDOW_ID( CHATTING_BTN_HANDCLAP ),
	WINDOW_ID( CHATTING_BTN_LOVE ),
	WINDOW_ID( CHATTING_BTN_REMEDY ),
	WINDOW_ID( CHATTING_BTN_THANKS ),
	WINDOW_ID( CHATTING_BTN_THERE ),
	WINDOW_ID( CHATTING_BTN_SCOLD ),
	WINDOW_ID( CHATTING_COMBOBOX ),
	WINDOW_ID( CHATTING_COMBO_BTN ),
	WINDOW_ID( CHATTING_EDITBOX ),
	WINDOW_ID( CHATTING_WHISPEREDITBOX ),
	WINDOW_ID( CHATTING_EDITRECT ), 

	/// 061130 LYW --- Add Window Id For Outside Chatting Dialog.
	WINDOW_ID( OSCHATTING_DLG ), 
	WINDOW_ID( OSCHATTING_BTN_TABNAME ), 
	WINDOW_ID( OSCHATTING_BTN_CLOSE ), 
	WINDOW_ID( OSCHATTING_LIST_WHOLE ), 

	// 061219 LYW --- Add window id for main system dialog.
	WINDOW_ID( MSD_DLG ),

	// 070102 LYW --- Add window id for new version of chatting system.
	//WINDOW_ID( CHAT_DLG ), 
	//// 070402 LYW --- Add window id for chatting dialog.
	//WINDOW_ID( CHAT_NORMAL ), 
	//WINDOW_ID( CHAT_PARTY ), 
	//WINDOW_ID( CHAT_FAMILY ), 
	//WINDOW_ID( CHAT_GUILD ), 
	//WINDOW_ID( CHAT_ALLIANCE ), 
	//WINDOW_ID( CHAT_TRADE ), 
	//WINDOW_ID( CHAT_SYSTEM ), 
	//WINDOW_ID( CHAT_ASSIST ), 
	//WINDOW_ID( CHAT_ASSIST_CLOSEBTN ), 

	//// 070416 LYW --- WindowIds : Add window id for pushup button.
	//WINDOW_ID( CHAT_BT_NORMAL ), 
	//WINDOW_ID( CHAT_BT_PARTY ),
	//WINDOW_ID( CHAT_BT_FAMILY ),
	//WINDOW_ID( CHAT_BT_GUILD ), 
	//WINDOW_ID( CHAT_BT_ALLIANCE ), 
	//WINDOW_ID( CHAT_BT_TRADE ), 
	//WINDOW_ID( CHAT_BT_SYSTEM ),
	//WINDOW_ID( CHAT_BT_ASSIST ),

	//WINDOW_ID( CHAT_INPUTBOX ), 
	//WINDOW_ID( CHAT_EXTENDBTN ), 

	//WINDOW_ID( CHAT_BGSTATIC ), 
	//WINDOW_ID( CHAT_BGEXTENDUP ), 
	//WINDOW_ID( CHAT_BGEXTENDDOWN ), 

	// 070528 LYW --- WindowIDs : Modified chatting dialog.
	WINDOW_ID( CHAT_DLG ),
	WINDOW_ID( CHAT_LIST ), 
	WINDOW_ID( CHAT_ASSIST_LIST ), 
	WINDOW_ID( CHAT_SHOUT_LIST ), 
	WINDOW_ID( CHAT_EDITBOX ), 
	WINDOW_ID( CHAT_EXTEND_BTN ), 
	WINDOW_ID( CHAT_REDUCTION_BTN ), 
	WINDOW_ID( CHAT_CLOSE_BTN ), 
	WINDOW_ID( CHAT_BTN_ALL ), 
	WINDOW_ID( CHAT_BTN_PARTY ), 
	WINDOW_ID( CHAT_BTN_FAMILY ), 
	WINDOW_ID( CHAT_BTN_GUILD ), 
	WINDOW_ID( CHAT_BTN_ALLIANCE ), 
	WINDOW_ID( CHAT_BTN_TRADE ), 
	WINDOW_ID( CHAT_BTN_SYSTEM ), 
	WINDOW_ID( CHAT_BTN_ASSIST ), 
	WINDOW_ID( CHAT_BTN_CHATROOM ),


	WINDOW_ID( MSD_MB_HELPER ), 
	WINDOW_ID( MSD_MB_GAMESYSTEM ), 
	WINDOW_ID( MSD_MB_ITEMMALL ), 
	WINDOW_ID( MSD_MB_SYSTEMSET ), 

	// 070115 LYW --- Add window id for static controls of sub dialog background image.
	WINDOW_ID( MSD_BG_SYSTEMSET ), 
	WINDOW_ID( MSD_BG_GAMESYSTEM ), 

	// 070115 LYW --- Add window id for title text of sub dialog.
	WINDOW_ID( MSD_TITLE_GAMESYSTEM ),
	WINDOW_ID( MSD_MARK_GAMESYSTEM ), 

	WINDOW_ID( MSD_GSBTN_CHARINFO ), 
	WINDOW_ID( MSD_GSBTN_SKILL ), 
	WINDOW_ID( MSD_GSBTN_QUEST ), 
	WINDOW_ID( MSD_GSBTN_GUILD ), 
	WINDOW_ID( MSD_GSBTN_FAMILY ), 
	WINDOW_ID( MSD_GSBTN_FRIEND ), 
	WINDOW_ID( MSD_GSBTN_MATCHING ), 
	WINDOW_ID( MSD_GSBTN_NOTE ), 
	WINDOW_ID( MSD_GSBTN_INVENTORY ), 
	// 071025 LYW --- WindowIDs : Add window id for help button of menu.
	WINDOW_ID( MSD_GSBTN_HELP ),

	// 080403 LYW --- WindowIDs : Add a window id to call main dialog of chatroom system.
	//WINDOW_ID( MSD_GSBTN_CHAT ), 

	// 070115 LYW --- Add window id for title text of sub dialog.
	WINDOW_ID( MSD_TITLE_SYSTEMSET ), 
	WINDOW_ID( MSD_MARK_SYSTEMSET ), 

	WINDOW_ID( MSD_SSBTN_GAME ), 
	WINDOW_ID( MSD_SSBTN_GRAPHIC ), 
	// 070115 LYW --- Delete this window id.
	//WINDOW_ID( MSD_SSBTN_SOUND ), 
	WINDOW_ID( MSD_SSBTN_CHARSELECT ), 
	WINDOW_ID( MSD_SSBTN_ENDGAME ), 

	WINDOW_ID( MSD_SHEET0 ), 
	WINDOW_ID( MSD_SHEET1 ), 
    	
//	WINDOW_ID(COI_DLG),
//	WINDOW_ID(COI_CB_OPTION01),
//	WINDOW_ID(COI_CB_OPTION02),
//	WINDOW_ID(COI_CB_OPTION03),
//	WINDOW_ID(COI_CB_OPTION04),
//	WINDOW_ID(COI_CB_OPTION05),
//	WINDOW_ID(COI_CB_OPTION06),
//	WINDOW_ID(COI_CB_OPTION07),
//	WINDOW_ID(COI_CB_OPTION08),
//	WINDOW_ID(COI_CB_OPTION09),
//	WINDOW_ID(COI_CB_OPTION10),
//	WINDOW_ID(COI_CB_OPTION11),
//	WINDOW_ID(COI_CB_OPTION12),

// LYJ 051017 구입노점상 추가

// 노점상 종류 선택 DLG
	WINDOW_ID(ST_OPTIONDLG),
	WINDOW_ID(SO_SELLBTN),
	WINDOW_ID(SO_BUYBTN),
	WINDOW_ID(SO_CANCELBTN),		// 210

// 구입 노점상 DLG
	WINDOW_ID(BS_STALLDLG),
	WINDOW_ID(BS_ICONGRID),
	WINDOW_ID(BS_TITLEEDIT),
	WINDOW_ID(BS_ENTER), 
	WINDOW_ID(BS_SELLBTN),
	WINDOW_ID(BS_SPBTN),
	WINDOW_ID(BS_MONEYEDIT),
	WINDOW_ID(BS_REGBTN),
	WINDOW_ID(BS_CLOSEBTN),

// 구입 아이템 등록 Dlg
	WINDOW_ID(BRS_STALLDLG),		// 220
	WINDOW_ID(BRS_CLOSEBTN),
	WINDOW_ID(BRS_TYPELIST),
	WINDOW_ID(BRS_ITEMLIST1),
	WINDOW_ID(BRS_ITEMLIST2), 
	WINDOW_ID(BRS_ITEMLIST3),
	WINDOW_ID(BRS_ITEMLIST4),
	WINDOW_ID(BRS_ITEMLIST5),
	WINDOW_ID(BRS_ITEMLIST6),
	WINDOW_ID(BRS_ITEMLIST7),
	WINDOW_ID(BRS_CLASSLIST),		// 230
	WINDOW_ID(BRS_VOLUMEEDIT),
	WINDOW_ID(BRS_MONEYEDIT),
	WINDOW_ID(BRS_REGBTN),
	WINDOW_ID(BRS_DELETEBTN), 
	WINDOW_ID(BRS_CLASSTEXT),
	WINDOW_ID(BRS_CLASSRECT1),
	WINDOW_ID(BRS_CLASSRECT2),
	WINDOW_ID(BRS_ITEMBIGRECT),
	WINDOW_ID(BRS_ITEMSMALLRECT1),
	WINDOW_ID(BRS_ITEMSMALLRECT2),	// 240
	
/*ⓒøea¡io*/
	WINDOW_ID(SSI_STALLDLG),
	WINDOW_ID(SSI_ICONGRID),
	WINDOW_ID(SSI_TITLEEDIT),
	WINDOW_ID(SSI_ENTER), 
	WINDOW_ID(SSI_BUYBTN),
	WINDOW_ID(SSI_REGISTBTN),
	WINDOW_ID(SSI_EDITBTN),
	WINDOW_ID(SSI_MONEYEDIT),
// LBS Aⓒ￢¡Æ￠® 03.09.18
	WINDOW_ID(SSI_REGISTENDBTN),
	WINDOW_ID(SSI_CLOSEBTN),		// 250

	// 071012 LYW --- WindowIDs : Add window for owner name of stall dialog.
	WINDOW_ID(SSI_OWNERTITLE),

// LBS 03.10.16 Npc￠￥e¡icA¡E￠?￠® ¡ic￠?e----
	WINDOW_ID(NSI_LISTDLG),
	WINDOW_ID(NSI_LISTDLG2), //070724 LYW --- WindowIDs : 새로운 npc 대화창 형식으로 바꾸면서, 리스트 다이얼로그 하나를 더 추가. 이름을 NSI_LISTDLG2로 한다.
	WINDOW_ID(NSI_TOPBTN),	 //070725 LYW --- WindowIDs : 새로운 npc 대화창 형식으로 바꾸면서, 처음화면, 대화종료 버튼을 추가함. 
	WINDOW_ID(NSI_ENDBTN),
	WINDOW_ID(NSI_SCRIPTDLG),
//----------------------------------	

// LBS 03.10.30 HelpA¡E￠?￠® ¡ic￠?e----
	WINDOW_ID(HI_LISTDLG),
	WINDOW_ID(HI_DLG),	
	WINDOW_ID(HI_EXPLANBTN),
	WINDOW_ID(HI_HANDLEBTN),	
	WINDOW_ID(HI_REARBTN),	
	WINDOW_ID(HI_ETCBTN),
	WINDOW_ID(HI_QnABTN),
	
//----------------------------------	

// LBS 03.11.07 ￥i￥i￠?iⓒoIA¡E￠?￠® ¡ic￠?e------
	WINDOW_ID(HSI_DLG),				// 260
	WINDOW_ID(HSI_NEXTBTN),
	WINDOW_ID(HSI_PREVBTN),
	WINDOW_ID(HSI_EXITBTN),
//-----------------------------------

/*¡ÆⓒªAeA¡E*/
	WINDOW_ID(CMI_CLOSEBTN), 
	WINDOW_ID(CMI_ALPHAGUAGE),
	WINDOW_ID(CMI_MONEYDLG),
	WINDOW_ID(CMI_MONEYOK),
	WINDOW_ID(CMI_MONEYCANCEL),	

	WINDOW_ID(CMI_MONEYSPIN),
	WINDOW_ID(CMI_MONEYSPINUP),		// 270
	WINDOW_ID(CMI_MONEYSPINDOWN),
	
/*¡ioaA¡E*/
	WINDOW_ID(DE_DEALERDLG),
	WINDOW_ID(DE_TABBTN1), 
	WINDOW_ID(DE_TABBTN2),
	WINDOW_ID(DE_TABBTN3),
	WINDOW_ID(DE_TABBTN4),
	WINDOW_ID(DE_TABBTN5),
	WINDOW_ID(DE_TABBTN6),

	WINDOW_ID(DE_TABBTN7),
	WINDOW_ID(DE_TABDLG1),			// 280
	WINDOW_ID(DE_TABDLG2),
	WINDOW_ID(DE_TABDLG3),
	WINDOW_ID(DE_TABDLG4), 
	WINDOW_ID(DE_TABDLG5),
	WINDOW_ID(DE_TABDLG6),
	WINDOW_ID(DE_TABDLG7),
	WINDOW_ID(DE_BUYITEM),
	WINDOW_ID(DE_SELLITEM),
	// 070503 LYW --- WindowIDs : Add window id for cancel button.
	WINDOW_ID(DE_CANCEL), 

	WINDOW_ID(DE_MONEYEDIT),
/*￠￥UAaA¡E*/
	WINDOW_ID(QI_QUICKDLG),			// 290
	WINDOW_ID(QI_QUICK2BTN),

	WINDOW_ID(QI_PREVPAGEBTN),
	WINDOW_ID(QI_NEXTPAGEBTN),
	WINDOW_ID(QI_TABNUMBER), 

	WINDOW_ID(QI1_QUICKSLOTDLG),
	WINDOW_ID(QI1_PAGESHEET1),
	WINDOW_ID(QI1_PAGESHEET2),
	WINDOW_ID(QI1_PAGESHEET3),

	// 080702 LYW --- WindowIDs : 확장 슬롯 추가 처리.
	WINDOW_ID(QI2_PREVPAGEBTN),
	WINDOW_ID(QI2_NEXTPAGEBTN),
	WINDOW_ID(QI2_TABNUMBER), 

	WINDOW_ID(QI2_QUICKSLOTDLG),
	WINDOW_ID(QI2_PAGESHEET1),
	WINDOW_ID(QI2_PAGESHEET2),
	WINDOW_ID(QI2_PAGESHEET3),

/* Aⓒø￠￢?AI ¡ÆOAIAo */
	WINDOW_ID(CG_GUAGEDLG),			
	WINDOW_ID(CG_GUAGELEVEL),	

	WINDOW_ID(CG_GUAGENAME),		// 300
	WINDOW_ID(CG_GUAGELIFE),
	WINDOW_ID(CG_GUAGEMANA), 
	WINDOW_ID(CG_GUAGEEXPPOINT),
	WINDOW_ID(CG_GUAGEEXPPOINTTEXT),
	WINDOW_ID(CG_GUAGEMUSSANG),
	WINDOW_ID(CG_MUSSANGSTART),
	WINDOW_ID(CG_MUSSANG1),
	WINDOW_ID(CG_MUSSANG2),
	WINDOW_ID(CG_GUAGELIFETEXT),
	WINDOW_ID(CG_GUAGEMANATEXT),

	// 070110 LYW --- Add window ids for character main dialog.
	WINDOW_ID( CG_MENUBOX ), 
	WINDOW_ID( CG_ST_MENU1BACK_TOP ), 
	WINDOW_ID( CG_ST_MENU1BACK_MIDDLE1 ), 
	WINDOW_ID( CG_ST_MENU1BACK_BOTTOM ), 
	WINDOW_ID( CG_ST_MENU2BACK_TOP ), 
	WINDOW_ID( CG_ST_MENU2BACK_MIDDLE1 ), 
	WINDOW_ID( CG_ST_MENU2BACK_MIDDLE2 ), 
	WINDOW_ID( CG_ST_MENU2BACK_BOTTOM ), 
	WINDOW_ID( CG_BT_MENU1_BUTTON1 ), 
	WINDOW_ID( CG_BT_MENU1_BUTTON2 ), 
	WINDOW_ID( CG_BT_MENU1_BUTTON3 ), 
	WINDOW_ID( CG_BT_MENU2_BUTTON1 ), 
	WINDOW_ID( CG_BT_MENU2_BUTTON2 ), 
	WINDOW_ID( CG_BT_MENU2_BUTTON3 ), 
	WINDOW_ID( CG_BT_MENU2_BUTTON4 ), 

	// 070117 LYW --- Add window ids for character face of charinfo dialog.
	WINDOW_ID( CG_ST_HERO_ELF_MAN ), 
	WINDOW_ID( CG_ST_HERO_ELF_WOMAN ), 
	WINDOW_ID( CG_ST_HERO_HUMAN_MAN ), 
	WINDOW_ID( CG_ST_HERO_HUMAN_WOMAN ), 

	WINDOW_ID(PA_MEMBER1DLG),	

	WINDOW_ID(PA_MEMBER2DLG),
	WINDOW_ID(PA_MEMBER3DLG),
	WINDOW_ID(PA_MEMBER4DLG),
	WINDOW_ID(PA_MEMBER5DLG),
	WINDOW_ID(PA_MEMBER6DLG),
	
	WINDOW_ID(PA_MEMBER1NAME),
	WINDOW_ID(PA_MEMBER2NAME),
	WINDOW_ID(PA_MEMBER3NAME),
	WINDOW_ID(PA_MEMBER4NAME),	
	WINDOW_ID(PA_MEMBER5NAME),	
	WINDOW_ID(PA_MEMBER6NAME),

	WINDOW_ID(PA_GUAGEMEMBER1LIFE),
	WINDOW_ID(PA_GUAGEMEMBER2LIFE),
	WINDOW_ID(PA_GUAGEMEMBER3LIFE),
	WINDOW_ID(PA_GUAGEMEMBER4LIFE),
	WINDOW_ID(PA_GUAGEMEMBER5LIFE),
	WINDOW_ID(PA_GUAGEMEMBER6LIFE),

	WINDOW_ID(PA_GUAGEMEMBER1MANA),
	WINDOW_ID(PA_GUAGEMEMBER2MANA),
	WINDOW_ID(PA_GUAGEMEMBER3MANA),	
	WINDOW_ID(PA_GUAGEMEMBER4MANA),
	WINDOW_ID(PA_GUAGEMEMBER5MANA),
	WINDOW_ID(PA_GUAGEMEMBER6MANA),
	
	WINDOW_ID(PA_MEMBER1LEVEL),
	WINDOW_ID(PA_MEMBER2LEVEL),
	WINDOW_ID(PA_MEMBER3LEVEL),
	WINDOW_ID(PA_MEMBER4LEVEL),
	WINDOW_ID(PA_MEMBER5LEVEL),
	WINDOW_ID(PA_MEMBER6LEVEL),	
	
	// 080318 LUJ, 파티원 버프 아이콘 토글 버튼
	WINDOW_ID(PA_MEMBER1_SKILL_ICON_BUTTON),
	WINDOW_ID(PA_MEMBER2_SKILL_ICON_BUTTON),
	WINDOW_ID(PA_MEMBER3_SKILL_ICON_BUTTON),
	WINDOW_ID(PA_MEMBER4_SKILL_ICON_BUTTON),
	WINDOW_ID(PA_MEMBER5_SKILL_ICON_BUTTON),
	WINDOW_ID(PA_MEMBER6_SKILL_ICON_BUTTON),

	WINDOW_ID(PA_BTNDLG),	
	//WINDOW_ID(PA_BACKGROUND),
	WINDOW_ID(PA_SECEDEBTN),	
	WINDOW_ID(PA_TRANSFERBTN),		
	WINDOW_ID(PA_FORCEDSECEDEBTN),
	WINDOW_ID(PA_BREAKUPBTN),
	WINDOW_ID(PA_ADDPARTYMEMBERBTN),
	WINDOW_ID(PA_WARSUGGESTBTN),

	// 080318 LUJ, 파티원 버프 아이콘 전체 토글 버튼
	WINDOW_ID(PA_SKILL_ICON_BUTTON),

	//WINDOW_ID(PA_OPTIONBTN),
	//WINDOW_ID(PA_MEMBERBTN),

	// 071002 LYW --- WindowIDs.h : Add window id for check box of party set.
	WINDOW_ID(PA_OP_RANDOM), 
	WINDOW_ID(PA_OP_DAMAGE), 
	WINDOW_ID(PA_OP_SEQUENCE), 

	
	WINDOW_ID(PA_CREATEDLG),
	WINDOW_ID(PA_CREATECOMBOX),
	WINDOW_ID(PA_CREATECOMBOXBTN),
	WINDOW_ID(PA_CREATEOK),
	WINDOW_ID(PA_CREATECANCEL),
	
	WINDOW_ID(PA_INVITEDLG),
	WINDOW_ID(PA_INVITER),
	WINDOW_ID(PA_INVITEDISTRIBUTE),
	WINDOW_ID(PA_INVITEOK),
	WINDOW_ID(PA_INVITECANCEL),

	// 070419 LYW --- WindowIDs : Add window id for character face to party member dialog.
	WINDOW_ID(PA_CHAR1_H_M), 
	WINDOW_ID(PA_CHAR2_H_M), 
	WINDOW_ID(PA_CHAR3_H_M), 
	WINDOW_ID(PA_CHAR4_H_M), 
	WINDOW_ID(PA_CHAR5_H_M), 
	WINDOW_ID(PA_CHAR6_H_M), 

	WINDOW_ID(PA_CHAR1_H_W), 
	WINDOW_ID(PA_CHAR2_H_W), 
	WINDOW_ID(PA_CHAR3_H_W), 
	WINDOW_ID(PA_CHAR4_H_W), 
	WINDOW_ID(PA_CHAR5_H_W), 
	WINDOW_ID(PA_CHAR6_H_W), 
	
	WINDOW_ID(PA_CHAR1_E_M), 
	WINDOW_ID(PA_CHAR2_E_M), 	
	WINDOW_ID(PA_CHAR3_E_M), 	
	WINDOW_ID(PA_CHAR4_E_M), 	
	WINDOW_ID(PA_CHAR5_E_M), 	
	WINDOW_ID(PA_CHAR6_E_M), 		

	WINDOW_ID(PA_CHAR1_E_W), 
	WINDOW_ID(PA_CHAR2_E_W), 
	WINDOW_ID(PA_CHAR3_E_W), 
	WINDOW_ID(PA_CHAR4_E_W), 
	WINDOW_ID(PA_CHAR5_E_W), 
	WINDOW_ID(PA_CHAR6_E_W), 

	/*GUILD */
	//create
	WINDOW_ID(GD_CREATEDLG),
	WINDOW_ID(GD_CNAME),
	WINDOW_ID(GD_CINTROTEXT),
	WINDOW_ID(GD_CLOCATION),
	WINDOW_ID(GD_CCREATEOKBTN),
	//guild
	WINDOW_ID(GD_GUILDDLG),
	WINDOW_ID(GD_NAME),
	WINDOW_ID(GD_LEVEL),
	WINDOW_ID(GD_SCORE),
	WINDOW_ID(GD_MASTER),
	WINDOW_ID(GD_MEMBERNUM),
	WINDOW_ID(GD_LOCATION),
	WINDOW_ID(GD_NAMES),
	WINDOW_ID(GD_LEVELS),
	WINDOW_ID(GD_MASTERS),
	WINDOW_ID(GD_MEMBERNUMS),
	WINDOW_ID(GD_LOCATIONS),
	WINDOW_ID(GD_UNIONNAMES),
	WINDOW_ID(GD_UNIONNAME),
	WINDOW_ID(GD_MEMBERINFOPUSHUPBTN),
	WINDOW_ID(GD_GUILFUNCPUSHUPBTN),
	WINDOW_ID(GD_RELATIONBTN),
	WINDOW_ID(GP_TIME),//Add 060803 by wonju
	WINDOW_ID(GD_MEMBERLIST),
	WINDOW_ID(GD_BANMEMBER),		//m_pGuildBtn[0]
	WINDOW_ID(GD_GIVEMEMBERNICK),
	WINDOW_ID(GD_GIVEMEMBERRANK),
	WINDOW_ID(GD_INVITEMEMBER),
	WINDOW_ID(GD_SECEDE),
	WINDOW_ID(GD_NOTICE),
	WINDOW_ID(GD_INVITEUNION),
	WINDOW_ID(GD_SECEDEUNION),
	WINDOW_ID(GD_REMOVEUNION),
	WINDOW_ID(GD_DECLARE),
	WINDOW_ID(GD_SUGGEST),
	WINDOW_ID(GD_SURRENDER),
	WINDOW_ID(GD_RETIRE_MASTER),
	WINDOW_ID(GD_CREATE_UNION),
	WINDOW_ID(GD_DISBAND_UNION),
	WINDOW_ID(GD_WAREHOUSE_RANK),
	WINDOW_ID(GD_MUNHA),
	// 080924 LUJ, 길드 멤버 직업 툴팁
	WINDOW_ID(GD_MEMBER_JOB_TOOLTIP),
	//Add 060803 by wonju---------------
	WINDOW_ID(GD_PLUSTIME),
	WINDOW_ID(GD_PLUSTIMESTART),
	WINDOW_ID(GD_POSITION),
	WINDOW_ID(GD_RANK),
	
	//GuildPlusTime - 항목
	WINDOW_ID(GD_POINT),
	WINDOW_ID(GD_PLUSTIMELIST),
	//------------------------------------
		
	//invite
	WINDOW_ID(GD_INVITEDlG),
	WINDOW_ID(GD_IINVITE),
	WINDOW_ID(GD_IOKBTN),
	WINDOW_ID(GD_ICANCELBTN),
	//guild mark
	WINDOW_ID(GDM_MARKREGISTDLG),
	WINDOW_ID(GDM_REGISTOKBTN),
	WINDOW_ID(GDM_NAMEEDIT),
	WINDOW_ID(GDM_TITLE),
	WINDOW_ID(GUM_REGISTOKBTN),
	//guild levelup
	WINDOW_ID(GD_LEVELUPDLG),
	WINDOW_ID(GD_LU1NOTCOMPLETE),
	WINDOW_ID(GD_LU2NOTCOMPLETE),
	WINDOW_ID(GD_LU3NOTCOMPLETE),
	WINDOW_ID(GD_LU4NOTCOMPLETE),
	WINDOW_ID(GD_LU5NOTCOMPLETE),
	WINDOW_ID(GD_LU6NOTCOMPLETE),
	WINDOW_ID(GD_LU7NOTCOMPLETE),
	WINDOW_ID(GD_LU8NOTCOMPLETE),
	WINDOW_ID(GD_LU1COMPLETE),
	WINDOW_ID(GD_LU2COMPLETE),
	WINDOW_ID(GD_LU3COMPLETE),
	WINDOW_ID(GD_LU4COMPLETE),
	WINDOW_ID(GD_LU5COMPLETE),
	WINDOW_ID(GD_LU6COMPLETE),
	WINDOW_ID(GD_LU7COMPLETE),
	WINDOW_ID(GD_LU8COMPLETE),
	WINDOW_ID(GD_LUOKBTN),
	WINDOW_ID(GD_LU1),
	WINDOW_ID(GD_LU2),
	WINDOW_ID(GD_LU3),
	WINDOW_ID(GD_LU4),
	WINDOW_ID(GD_LU5),
	WINDOW_ID(GD_LU6),
	WINDOW_ID(GD_LU7),
	WINDOW_ID(GD_LU8),
	//guild nick name 
	WINDOW_ID(GD_NICKNAMEDLG),
	WINDOW_ID(GD_NICKTEXTAREA),
	WINDOW_ID(GD_NICKNAMEEDIT),
	WINDOW_ID(GD_NICKTITLE),
	WINDOW_ID(GD_NREGISTOKBTN),	
	//guild change rank
	WINDOW_ID(GDR_RANKDLG),
	WINDOW_ID(GDR_DRANKCOMBOBOX),
	WINDOW_ID(GDR_RANKCOMBOBOX),
	WINDOW_ID(GDR_DOKBTN),
	WINDOW_ID(GDR_OKBTN),
	WINDOW_ID(GDR_CANCELBTN),
	WINDOW_ID(GDR_MEMBERNAME),
	WINDOW_ID(GDR_TITLE),
	// guild warehouse rank
	WINDOW_ID(GDWHR_RANKDLG),
	WINDOW_ID(GDWHR_OKBTN),
	WINDOW_ID(GDWHR_CANCELBTN),
	WINDOW_ID(GDWHR_RANKCOMBOBOX),
	//guild warehouse
	WINDOW_ID(GDW_WAREHOUSEDLG),
	WINDOW_ID(GDW_WAREHOUSE1BTN),
	WINDOW_ID(GDW_WAREHOUSE2BTN),
	WINDOW_ID(GDW_TABDLG1),
	WINDOW_ID(GDW_TABDLG2),
	WINDOW_ID(GDW_PUTINMONEYBTN),
	WINDOW_ID(GDW_PUTOUTMONEYBTN),
	//WINDOW_ID(GDW_CLOSEBTN),
	WINDOW_ID(GDW_MONEY),
	//guild union
	WINDOW_ID(GDU_CREATEDLG),
	WINDOW_ID(GDU_NAME),
	WINDOW_ID(GDU_TEXT),	
	WINDOW_ID(GDU_OKBTN),
	WINDOW_ID(GUD_CANCELBTN),

	// guild revival
	WINDOW_ID(GD_REVIVAL_AT_TOWN),
	WINDOW_ID(GD_REVIVALDLG),

	//C¡I¡¾ⓒo
	WINDOW_ID(PYO_STORAGEDLG),
	WINDOW_ID(PYO_STORAGELISTBTN),
	WINDOW_ID(PYO_NOBUYBTN),
	WINDOW_ID(PYO_STORAGEINFO1),
	WINDOW_ID(PYO_STORAGEINFO2),
	WINDOW_ID(PYO_STORAGEINFO3),
	WINDOW_ID(PYO_STORAGE1BTN),
	WINDOW_ID(PYO_STORAGE2BTN),
	WINDOW_ID(PYO_STORAGE3BTN),
	WINDOW_ID(PYO_STORAGE4BTN),
	WINDOW_ID(PYO_STORAGE5BTN),
	WINDOW_ID(PYO_STORAGELCTRL),
	WINDOW_ID(PYO_STORAGEHAVE),
	WINDOW_ID(PYO_STORAGEHAVESTC),
	WINDOW_ID(PYO_BUYSTORAGEBTN),
	WINDOW_ID(PYO_MONEY),
	WINDOW_ID(PYO_MONEYIMG),
	WINDOW_ID(PYO_MONEYBACKIMG),
	WINDOW_ID(PYO_PUTINMONEYBTN),
	WINDOW_ID(PYO_PUTOUTMONEYBTN),
	WINDOW_ID(PYO_WAREITEM1),
	WINDOW_ID(PYO_WAREITEM2),
	WINDOW_ID(PYO_WAREITEM3),
	WINDOW_ID(PYO_WAREITEM4),
	WINDOW_ID(PYO_WAREITEM5),
	WINDOW_ID(PYO_NOWARE),
	WINDOW_ID(PYO_NOWARE1),
	WINDOW_ID(PYO_NOBUYSTORAGEBTN),
	WINDOW_ID(PYO_WAREIMAGE),
	// 070326 LYW --- WindowIDs : Add window id for close button.
	WINDOW_ID(PYO_STORAGE_CLOSE), 

	//AEAo
	WINDOW_ID(NOTE_NOTEDLG),
	WINDOW_ID(NOTE_NOTELISTLCTL),
	WINDOW_ID(NOTE_NOTELISTCHK1),
	WINDOW_ID(NOTE_NOTELISTCHK2),
	WINDOW_ID(NOTE_NOTELISTCHK3),
	WINDOW_ID(NOTE_NOTELISTCHK4),
	WINDOW_ID(NOTE_NOTELISTCHK5),
	WINDOW_ID(NOTE_NOTELISTCHK6),
	WINDOW_ID(NOTE_NOTELISTCHK7),
	WINDOW_ID(NOTE_NOTELISTCHK8),
	WINDOW_ID(NOTE_NOTELISTCHK9),
	WINDOW_ID(NOTE_NOTELISTCHK10),
	WINDOW_ID(NOTE_NOTELISTCHK11),
	WINDOW_ID(NOTE_WRITENOTEBTN),
	WINDOW_ID(NOTE_DELNOTEBTN),
	WINDOW_ID(NOTE_TABBTN1),
	WINDOW_ID(NOTE_TABBTN2),
	WINDOW_ID(NOTE_PAGE1BTN),
	WINDOW_ID(NOTE_PAGE2BTN),
	WINDOW_ID(NOTE_PAGE3BTN),
	WINDOW_ID(NOTE_PAGE4BTN),
	WINDOW_ID(NOTE_PAGE5BTN),

	//A¡I¡¾￠￢
	WINDOW_ID(FRI_FRIENDDLG),
	WINDOW_ID(FRI_FRIENDLISTLCTL),
	WINDOW_ID(FRI_FRIENDLISTCHK1),
	WINDOW_ID(FRI_FRIENDLISTCHK2),
	WINDOW_ID(FRI_FRIENDLISTCHK3),
	WINDOW_ID(FRI_FRIENDLISTCHK4),
	WINDOW_ID(FRI_FRIENDLISTCHK5),
	WINDOW_ID(FRI_FRIENDLISTCHK6),
	WINDOW_ID(FRI_FRIENDLISTCHK7),
	WINDOW_ID(FRI_FRIENDLISTCHK8),
	WINDOW_ID(FRI_FRIENDLISTCHK9),
	WINDOW_ID(FRI_FRIENDLISTCHK10),
	WINDOW_ID(FRI_PAGE1BTN),
	WINDOW_ID(FRI_PAGE2BTN),
	WINDOW_ID(FRI_PAGE3BTN),
	WINDOW_ID(FRI_ADDFRIENDBTN),
	WINDOW_ID(FRI_DELFRIENDBTN),
	WINDOW_ID(FRI_SENDNOTEBTN),
	WINDOW_ID(FRI_SENDWHISPERBTN),
	
	//ⓒoI￠￥I AEAo
	WINDOW_ID(NOTE_MRTITLE),
	WINDOW_ID(NOTE_MWTITLE),
	WINDOW_ID(NOTE_MINNOTEDLG),
	WINDOW_ID(NOTE_MRECEIVEREDIT),
	WINDOW_ID(NOTE_MRNOTETEXTREA),
	WINDOW_ID(NOTE_MWNOTETEXTREA),
	WINDOW_ID(NOTE_MSENDOKBTN),
	WINDOW_ID(NOTE_MSENDCANCELBTN),
	WINDOW_ID(NOTE_MRECEIVER),
	WINDOW_ID(NOTE_MSENDER),
	WINDOW_ID(NOTE_MSENDERSTC),
	WINDOW_ID(NOTE_MREPLYBTN),
	WINDOW_ID(NOTE_MDELETEBTN),
	
	//ⓒoI￠￥ICw¡i
	WINDOW_ID(FRI_MINIFRIENDDLG),
	WINDOW_ID(FRI_NAME),
	WINDOW_ID(FRI_NAMEEDIT),
	WINDOW_ID(FRI_ADDOKBTN),
	WINDOW_ID(FRI_ADDCANCELBTN),	

	
	
//KES DIALOG
/*￠￢AA¨I¡¤I¨u¨u¨¡AA¡E*/
	WINDOW_ID(MAC_MACRODLG),			//￠￥UAI¨uo¡¤I¡¾¡¿ ¨uⓒª¨u¡ⓒ￠?I ￠￢A¨u¨¡¨uⓒ￢ CN￠￥U.
	WINDOW_ID(MAC_BTN_SAVE),
	WINDOW_ID(MAC_BTN_DEFAULT),
	WINDOW_ID(MAC_EB_QUICKITEM01),
	WINDOW_ID(MAC_EB_QUICKITEM02),
	WINDOW_ID(MAC_EB_QUICKITEM03),
	WINDOW_ID(MAC_EB_QUICKITEM04),
	WINDOW_ID(MAC_EB_QUICKITEM05),
	WINDOW_ID(MAC_EB_QUICKITEM06),
	WINDOW_ID(MAC_EB_QUICKITEM07),
	WINDOW_ID(MAC_EB_SKILLDLG),
	WINDOW_ID(MAC_EB_INVENTORYDLG),
	WINDOW_ID(MAC_EB_CHARACTERDLG),
	WINDOW_ID(MAC_EB_MUNPADLG),
	WINDOW_ID(MAC_EB_MINIMAP),

	WINDOW_ID(MAC_EB_QUESTDLG),
	WINDOW_ID(MAC_EB_EXITDLG),
	WINDOW_ID(MAC_EB_CLOSE_ACTIVEDLG),
	WINDOW_ID(MAC_EB_MOVEMODE),
	WINDOW_ID(MAC_EB_GYUNGGONG),
	WINDOW_ID(MAC_EB_PGDN_QUICKSLOT),
	WINDOW_ID(MAC_EB_PGUP_QUICKSLOT),
	WINDOW_ID(MAC_EB_UNGIMODE),
	WINDOW_ID(MAC_EB_PEACEMODE),
	WINDOW_ID(MAC_EB_AUTOATTACK),
	WINDOW_ID(MAC_EB_CAMERAMOVE_ZOOMIN),
	WINDOW_ID(MAC_EB_CAMERAMOVE_ZOOMOUT),

	WINDOW_ID(MAC_EB_FREEVIEW),
	WINDOW_ID(MAC_EB_BACKVIEW),
	WINDOW_ID(MAC_EB_QUARTERVIEW),
	WINDOW_ID(MAC_EB_LOADVIEW),
	WINDOW_ID(MAC_EB_SAVEVIEW),
	WINDOW_ID(MAC_EB_SCREENCAPTURE),
	WINDOW_ID(MAC_EB_CAMERAMOVE_UP),
	WINDOW_ID(MAC_EB_CAMERAMOVE_DOWN),
	WINDOW_ID(MAC_EB_CAMERAMOVE_RIGHT),
	WINDOW_ID(MAC_EB_CAMERAMOVE_LEFT),

/*￠?E¨uCA¡E*/
	WINDOW_ID(OTI_TABDLG),
	WINDOW_ID(OTI_SHEET1),
	WINDOW_ID(OTI_SHEET2),
	WINDOW_ID(OTI_SHEET3),
	WINDOW_ID(OTI_SHEET4),	
	WINDOW_ID(OTI_BTN_RESET),
	WINDOW_ID(OTI_BTN_OK),
	WINDOW_ID(OTI_BTN_PREVIEW),
	WINDOW_ID(OTI_BTN_CANCEL),
	WINDOW_ID(OTI_CB_NODEAL),
	WINDOW_ID(OTI_CB_NOPARTY),
	WINDOW_ID(OTI_CB_NOFRIEND),
	WINDOW_ID(OTI_CB_NOFIGHT),
	WINDOW_ID(OTI_CB_MUNPANAME),
	WINDOW_ID(OTI_CB_PARTYNAME),
	WINDOW_ID(OTI_CB_OTHERSNAME),
	WINDOW_ID(OTI_CB_GAMETIP),
	WINDOW_ID(OTI_CB_MEMBERDAMAGE),
	WINDOW_ID(OTI_PB_CHATMODE),
	WINDOW_ID(OTI_PB_MACROMODE),

	WINDOW_ID(OTI_CB_MUNPAPR),

	//WINDOW_ID( OTI_CB_WHISPER ),
	//WINDOW_ID( OTI_CB_TALK ),
	//WINDOW_ID( OTI_CB_BALLOON ),
	//WINDOW_ID( OTI_CB_SYSTEM ),
	//WINDOW_ID( OTI_CB_EXPERIENCE1 ),
	////WINDOW_ID( OTI_CB_EXPERIENCE2 ),
	//WINDOW_ID( OTI_CB_ITEM1 ),
	////WINDOW_ID( OTI_CB_ITEM2 ),
	//WINDOW_ID( OTI_CB_MONEY1 ),
	////WINDOW_ID( OTI_CB_MONEY2 ),
	//WINDOW_ID( OTI_CB_COMBAT1 ),
	////WINDOW_ID( OTI_CB_COMBAT2 ),
	//WINDOW_ID( OTI_CB_EMOTICON ),
	//WINDOW_ID( OTI_GB_CHATALPHA ), 
	//WINDOW_ID( OTI_GB_CHATALPHA2 ), 

	WINDOW_ID(OTI_BTN_SETCHAT),
	WINDOW_ID(OTI_BTN_SETMACRO),
	WINDOW_ID(OTI_CB_NOWHISPER),
	WINDOW_ID(OTI_CB_NOCHATTING),
	WINDOW_ID(OTI_CB_NOBALLOON),
	//WINDOW_ID(OTI_CB_AUTOHIDE),
	WINDOW_ID(OTI_CB_NOPARTYCHAT), 
	WINDOW_ID(OTI_CB_NOFAMILYCHAT),
	WINDOW_ID(OTI_CB_WORLDHIDE),
	WINDOW_ID(OTI_CB_MUNPAHIDE),
	WINDOW_ID(OTI_CB_ALLMUNPAHIDE),
	WINDOW_ID(OTI_CB_NOSYSTEMMSG),
	WINDOW_ID(OTI_CB_NOACQUIREMSG),
	WINDOW_ID(OTI_CB_NOITEMMSG),
	WINDOW_ID(OTI_GB_GAMMA),
	WINDOW_ID(OTI_GB_SIGHT),
	WINDOW_ID(OTI_CB_CURSOR),
	WINDOW_ID(OTI_CB_HEROSHADOW),
	WINDOW_ID(OTI_CB_MONSTERSHADOW),
	WINDOW_ID(OTI_CB_OTHERSSHADOW),
	//SW060904 Add MapAmbientCtrlOptn
	WINDOW_ID(OTI_CB_AMBIENT),

	//SW050822 Add GraphicCtrlOptn
	WINDOW_ID(OTI_CB_AUTOCONTROL),
	WINDOW_ID(OTI_PB_BASICGRAPHIC),
	WINDOW_ID(OTI_PB_DOWNGRAPHIC),
	WINDOW_ID(OTI_PB_BASICEFFECT),
	WINDOW_ID(OTI_PB_ONEEFFECT),
	WINDOW_ID(OTI_CB_SNOWEFFECT), // 2005.12.29일 추가 

	WINDOW_ID(OTI_TEXT_SIGHT),
	WINDOW_ID(OTI_TEXT_HEROSHADOW),
	WINDOW_ID(OTI_TEXT_MONSTERSHADOW),
	WINDOW_ID(OTI_TEXT_OTHERSSHADOW),
	WINDOW_ID(OTI_TEXT_BASICGRAPHIC),
	WINDOW_ID(OTI_TEXT_DOWNGRAPHIC),
	WINDOW_ID(OTI_TEXT_BASICEFFECT),
	WINDOW_ID(OTI_TEXT_ONEEFFECT),
//	WINDOW_ID(OTI_PB_ALLOFFEFFECT),
	
	WINDOW_ID(OTI_CB_BGMSOUND),
	WINDOW_ID(OTI_CB_ENVSOUND),
	WINDOW_ID(OTI_GB_BGMSOUND),
	WINDOW_ID(OTI_GB_ENVSOUND),

	// 071017 LYW --- WindowIDs : Add window ids for tutorial dialog part.
	WINDOW_ID(TUTORIAL_DLG), 
		WINDOW_ID(TTR_SPEECH_LIST), 
		WINDOW_ID(TTR_OKBTN), 
		WINDOW_ID(TTR_PREVBTN), 
		WINDOW_ID(TTR_NEXTBTN), 
		WINDOW_ID(TTR_PASSBTN),
		WINDOW_ID(TTR_SP_BACK), 

	// 071017 LYW --- WindowIDs : Add window ids for help dialog part.
	WINDOW_ID(HELP_DLG), 
		WINDOW_ID(HD_LINKLIST), 
		WINDOW_ID(HD_SHOWTUTORIAL), 
		WINDOW_ID(HD_START), 
		WINDOW_ID(HD_END), 

	// 071023 LYW --- WindowIDs : Add window ids for tutorial button dialog.
	WINDOW_ID(TUTORIALBTN_DLG), 
		WINDOW_ID(TTR_NOTICEBTN), 

	WINDOW_ID(ITEMMALLBTN_DLG), 
		WINDOW_ID(ITM_NOTICEBTN), 

	WINDOW_ID(ITEMPOPUP_DLG), 
	WINDOW_ID(ITEMPOPUP_MIDDLE),
	WINDOW_ID(ITEMPOPUP_BOTTOM),
	WINDOW_ID(ITEMPOPUP_TEXT),

	//071130 LYW --- WindowIDs : Add window ids for map move dialog.
	WINDOW_ID(MAPMOVE_DLG),
		WINDOW_ID(MMD_MAPLIST),
		WINDOW_ID(MMD_MOVEBTN), 
		WINDOW_ID(MMD_CLOSEBTN),
		WINDOW_ID(MMD_XCLOSEBTN),

	// 071228 LYW --- WindowIDs : Add window ids to change name dialog.
	WINDOW_ID(CHANGENAME_DLG),
		WINDOW_ID(NAME_BOX),
		WINDOW_ID(CHANGE_BTN), 
		WINDOW_ID(CANCEL_BTN), 

	// 080109 LYW --- WindowIDs : Add window ids for number pad dialog.
	WINDOW_ID(NUMBERPAD_DLG),
		WINDOW_ID(NUMBERPAD_NUMBERBOX),
		WINDOW_ID(NUMBERPAD_0),
		WINDOW_ID(NUMBERPAD_1),
		WINDOW_ID(NUMBERPAD_2),
		WINDOW_ID(NUMBERPAD_3),
		WINDOW_ID(NUMBERPAD_4),
		WINDOW_ID(NUMBERPAD_5),
		WINDOW_ID(NUMBERPAD_6),
		WINDOW_ID(NUMBERPAD_7),
		WINDOW_ID(NUMBERPAD_8),
		WINDOW_ID(NUMBERPAD_9),
		WINDOW_ID(NUMBERPAD_BACKSPACE),



/*~¡¤aA¡E*/
	WINDOW_ID(EXT_DIALOG),
	WINDOW_ID(EXT_BTN_EXITGAME),
	WINDOW_ID(EXT_BTN_SELECTCHAR),
	WINDOW_ID(EXT_BTN_OPTION),
	WINDOW_ID(EXT_BTN_EMERGENCY),

	// desc_hseos_몬스터미터_01
	// S 몬스터미터 추가 added by hseos 2007.04.09
	WINDOW_ID(MONSTERMETER_DLG),
	WINDOW_ID(MONSTERMETER_DLG_PLAYTIME),
	WINDOW_ID(MONSTERMETER_DLG_KILLMONNUM),
	WINDOW_ID(MONSTERMETER_DLG_GIFTTIME1),
	WINDOW_ID(MONSTERMETER_DLG_GIFTTIME2),
	WINDOW_ID(MONSTERMETER_DLG_GIFTTIME3),
	// E 몬스터미터 추가 added by hseos 2007.04.09

/*¡¾ⓒøE?A¡E*/
	WINDOW_ID(XCI_DIALOG),	
	WINDOW_ID(XCI_BTN_CLOSE),
	WINDOW_ID(XCI_BTN_LOCK),
	WINDOW_ID(XCI_BTN_EXCHANGE),
	WINDOW_ID(XCI_BTN_EXIT),
	WINDOW_ID(XCI_BTN_INPUTMONEY),
	WINDOW_ID(XCI_EB_MYMONEY),
	WINDOW_ID(XCI_EB_OPMONEY),
	WINDOW_ID(XCI_ICD_MINE),
	WINDOW_ID(XCI_ICD_OPPOSITE),
	WINDOW_ID(XCI_INFO1),
	WINDOW_ID(XCI_INFO2),
/*Aⓒø￠￢?AI¡ioAAA¡E*/
	WINDOW_ID(CSS_DIALOG),
	WINDOW_ID(CSS_BTN_PK),
	WINDOW_ID(CSS_BTN_MOVE),
	WINDOW_ID(CSS_BTN_KYUNGGONG),
	WINDOW_ID(CSS_BTN_PEACEWAR),
	WINDOW_ID(CSS_BTN_UNGI),
/*Aⓒø￠￢?AI Ac¡iyA¡E*/
	WINDOW_ID(CR_DIALOG),
	WINDOW_ID(CR_PRESENTSPOT),
	WINDOW_ID(CR_LOGINSPOT),
	WINDOW_ID(CR_TOWNSPOT),
	// 070112 LYW --- Add window id for textarea of revive dialog.
	WINDOW_ID(CR_TEXTAREA), 

	WINDOW_ID(CR_S1),
	WINDOW_ID(CR_S2),
	
	WINDOW_ID(ITD_UPGRADEDLG),
	WINDOW_ID(ITD_UPGRADEGRID),
	WINDOW_ID(ITD_UPGRADE_RESULT),
	WINDOW_ID(ITD_UPGRADE_OKBTN),
	WINDOW_ID(ITD_UPGRADE_CANCELBTN),

	// 080228 LUJ, 인챈트 보호 때 표시되는 이미지
	WINDOW_ID(ITD_UPGRADE_TITLE),
	WINDOW_ID(ITD_UPGRADE_PROTECT_TITLE),
	WINDOW_ID(ITD_UPGRADE_PROTECT_SYMBOL),
	
	WINDOW_ID(ITMD_MIXDLG),
	WINDOW_ID(ITMD_MIXICONTITLE),
	WINDOW_ID(ITMD_MIXICONDLG),
	WINDOW_ID(ITMD_MIXICONGRIDDLG),
	WINDOW_ID(ITMD_MIXMATERIALS),
	WINDOW_ID(ITMD_MIXOKBTN),
	WINDOW_ID(ITMD_MIXCANCELBTN),
	WINDOW_ID(ITMD_MIXDESCRIPTION),

	// 080228 LUJ, 조합 보호 때 표시되는 이미지
	WINDOW_ID(ITMD_MIX_PROTECT_TITLE),
	WINDOW_ID(ITMD_MIX_PROTECT_SYMBOL),

	WINDOW_ID(PROGRESS_DIALOG),
	WINDOW_ID(PROGRESS_DIALOG_TEXT),
	WINDOW_ID(PROGRESS_DIALOG_GAUGE),
	WINDOW_ID(PROGRESS_DIALOG_CLOSE),

	WINDOW_ID(ITR_REINFORCETITLE),
	WINDOW_ID(ITR_REINFORCEDLG),
	WINDOW_ID(ITR_REINFORCEICONDLG),
	WINDOW_ID(ITR_REINFORCEICONGRIDDLG),

	// 080228 LUJ, 강화 보호 때 표시되는 이미지
	WINDOW_ID(ITR_REINFORCE_PROTECT_TITLE),
	WINDOW_ID(ITR_REINFORCE_PROTECT_SYMBOL),

	// 06. 02. 강화 재료 안내 인터페이스 추가 - 이영준
	WINDOW_ID(ITR_RFGUIDEBTN),
	WINDOW_ID(ITR_REINFORCEOKBTN),
	WINDOW_ID(ITR_REINFORCECANCELBTN),
	WINDOW_ID(ITR_REINFORCEGRAVITY),

	// 06. 02. 강화 재료 안내 인터페이스 추가 - 이영준
	WINDOW_ID(RFGUIDE_DLG),
	WINDOW_ID(RFGUIDE_BTN1),
	WINDOW_ID(RFGUIDE_BTN2),
	WINDOW_ID(RFGUIDE_BTN3),
	WINDOW_ID(RFGUIDE_BTN4),
	WINDOW_ID(RFGUIDE_BTN5),
	WINDOW_ID(RFGUIDE_BTN6),
	WINDOW_ID(RFGUIDE_BTN7),
	WINDOW_ID(RFGUIDE_BTN8),
	WINDOW_ID(RFGUIDE_BTN9),
	WINDOW_ID(RFGUIDE_BTN10),
	WINDOW_ID(RFGUIDE_SHEET1),
	WINDOW_ID(RFGUIDE_SHEET2),
	WINDOW_ID(RFGUIDE_SHEET3),
	WINDOW_ID(RFGUIDE_SHEET4),
	WINDOW_ID(RFGUIDE_SHEET5),
	WINDOW_ID(RFGUIDE_SHEET6),
	WINDOW_ID(RFGUIDE_SHEET7),
	WINDOW_ID(RFGUIDE_SHEET8),
	WINDOW_ID(RFGUIDE_SHEET9),
	WINDOW_ID(RFGUIDE_SHEET10),
	WINDOW_ID(RFGUIDE_SHEET1_TITLE1),
	WINDOW_ID(RFGUIDE_SHEET1_TITLE2),
	WINDOW_ID(RFGUIDE_SHEET1_TITLE3),
	WINDOW_ID(RFGUIDE_SHEET1_TITLE4),
	WINDOW_ID(RFGUIDE_SHEET1_TITLE5),
	WINDOW_ID(RFGUIDE_SHEET1_TITLE6),
	WINDOW_ID(RFGUIDE_SHEET1_TITLE7),
	WINDOW_ID(RFGUIDE_SHEET1_TITLE8),
	WINDOW_ID(RFGUIDE_SHEET1_TITLE9),
	WINDOW_ID(RFGUIDE_SHEET1_TITLE10),

	WINDOW_ID(RFGUIDE_SHEET1_DESC1),
	WINDOW_ID(RFGUIDE_SHEET1_DESC2),
	WINDOW_ID(RFGUIDE_SHEET1_DESC3),
	WINDOW_ID(RFGUIDE_SHEET1_DESC4),
	WINDOW_ID(RFGUIDE_SHEET1_DESC5),
	WINDOW_ID(RFGUIDE_SHEET1_DESC6),
	WINDOW_ID(RFGUIDE_SHEET1_DESC7),
	WINDOW_ID(RFGUIDE_SHEET1_DESC8),
	WINDOW_ID(RFGUIDE_SHEET1_DESC9),
	WINDOW_ID(RFGUIDE_SHEET1_DESC10),	

	WINDOW_ID(RFGUIDE_SHEET2_TITLE1),
	WINDOW_ID(RFGUIDE_SHEET2_TITLE2),
	WINDOW_ID(RFGUIDE_SHEET2_TITLE3),
	WINDOW_ID(RFGUIDE_SHEET2_TITLE4),
	WINDOW_ID(RFGUIDE_SHEET2_TITLE5),
	WINDOW_ID(RFGUIDE_SHEET2_TITLE6),
	WINDOW_ID(RFGUIDE_SHEET2_TITLE7),
	WINDOW_ID(RFGUIDE_SHEET2_TITLE8),
	WINDOW_ID(RFGUIDE_SHEET2_TITLE9),
	WINDOW_ID(RFGUIDE_SHEET2_TITLE10),

	WINDOW_ID(RFGUIDE_SHEET2_DESC1),
	WINDOW_ID(RFGUIDE_SHEET2_DESC2),
	WINDOW_ID(RFGUIDE_SHEET2_DESC3),
	WINDOW_ID(RFGUIDE_SHEET2_DESC4),
	WINDOW_ID(RFGUIDE_SHEET2_DESC5),
	WINDOW_ID(RFGUIDE_SHEET2_DESC6),
	WINDOW_ID(RFGUIDE_SHEET2_DESC7),
	WINDOW_ID(RFGUIDE_SHEET2_DESC8),
	WINDOW_ID(RFGUIDE_SHEET2_DESC9),
	WINDOW_ID(RFGUIDE_SHEET2_DESC10),

	WINDOW_ID(RFGUIDE_SHEET3_TITLE1),
	WINDOW_ID(RFGUIDE_SHEET3_TITLE2),
	WINDOW_ID(RFGUIDE_SHEET3_TITLE3),
	WINDOW_ID(RFGUIDE_SHEET3_TITLE4),
	WINDOW_ID(RFGUIDE_SHEET3_TITLE5),
	WINDOW_ID(RFGUIDE_SHEET3_TITLE6),
	WINDOW_ID(RFGUIDE_SHEET3_TITLE7),
	WINDOW_ID(RFGUIDE_SHEET3_TITLE8),
	WINDOW_ID(RFGUIDE_SHEET3_TITLE9),
	WINDOW_ID(RFGUIDE_SHEET3_TITLE10),

	WINDOW_ID(RFGUIDE_SHEET3_DESC1),
	WINDOW_ID(RFGUIDE_SHEET3_DESC2),
	WINDOW_ID(RFGUIDE_SHEET3_DESC3),
	WINDOW_ID(RFGUIDE_SHEET3_DESC4),
	WINDOW_ID(RFGUIDE_SHEET3_DESC5),
	WINDOW_ID(RFGUIDE_SHEET3_DESC6),
	WINDOW_ID(RFGUIDE_SHEET3_DESC7),
	WINDOW_ID(RFGUIDE_SHEET3_DESC8),
	WINDOW_ID(RFGUIDE_SHEET3_DESC9),
	WINDOW_ID(RFGUIDE_SHEET3_DESC10),

	WINDOW_ID(RFGUIDE_SHEET4_TITLE1),
	WINDOW_ID(RFGUIDE_SHEET4_TITLE2),
	WINDOW_ID(RFGUIDE_SHEET4_TITLE3),
	WINDOW_ID(RFGUIDE_SHEET4_TITLE4),
	WINDOW_ID(RFGUIDE_SHEET4_TITLE5),
	WINDOW_ID(RFGUIDE_SHEET4_TITLE6),
	WINDOW_ID(RFGUIDE_SHEET4_TITLE7),
	WINDOW_ID(RFGUIDE_SHEET4_TITLE8),
	WINDOW_ID(RFGUIDE_SHEET4_TITLE9),
	WINDOW_ID(RFGUIDE_SHEET4_TITLE10),

	WINDOW_ID(RFGUIDE_SHEET4_DESC1),
	WINDOW_ID(RFGUIDE_SHEET4_DESC2),
	WINDOW_ID(RFGUIDE_SHEET4_DESC3),
	WINDOW_ID(RFGUIDE_SHEET4_DESC4),
	WINDOW_ID(RFGUIDE_SHEET4_DESC5),
	WINDOW_ID(RFGUIDE_SHEET4_DESC6),
	WINDOW_ID(RFGUIDE_SHEET4_DESC7),
	WINDOW_ID(RFGUIDE_SHEET4_DESC8),
	WINDOW_ID(RFGUIDE_SHEET4_DESC9),
	WINDOW_ID(RFGUIDE_SHEET4_DESC10),

	WINDOW_ID(RFGUIDE_SHEET5_TITLE1),
	WINDOW_ID(RFGUIDE_SHEET5_TITLE2),
	WINDOW_ID(RFGUIDE_SHEET5_TITLE3),
	WINDOW_ID(RFGUIDE_SHEET5_TITLE4),
	WINDOW_ID(RFGUIDE_SHEET5_TITLE5),
	WINDOW_ID(RFGUIDE_SHEET5_TITLE6),
	WINDOW_ID(RFGUIDE_SHEET5_TITLE7),
	WINDOW_ID(RFGUIDE_SHEET5_TITLE8),
	WINDOW_ID(RFGUIDE_SHEET5_TITLE9),
	WINDOW_ID(RFGUIDE_SHEET5_TITLE10),

	WINDOW_ID(RFGUIDE_SHEET5_DESC1),
	WINDOW_ID(RFGUIDE_SHEET5_DESC2),
	WINDOW_ID(RFGUIDE_SHEET5_DESC3),
	WINDOW_ID(RFGUIDE_SHEET5_DESC4),
	WINDOW_ID(RFGUIDE_SHEET5_DESC5),
	WINDOW_ID(RFGUIDE_SHEET5_DESC6),
	WINDOW_ID(RFGUIDE_SHEET5_DESC7),
	WINDOW_ID(RFGUIDE_SHEET5_DESC8),
	WINDOW_ID(RFGUIDE_SHEET5_DESC9),
	WINDOW_ID(RFGUIDE_SHEET5_DESC10),

	WINDOW_ID(RFGUIDE_SHEET6_TITLE1),
	WINDOW_ID(RFGUIDE_SHEET6_TITLE2),
	WINDOW_ID(RFGUIDE_SHEET6_TITLE3),
	WINDOW_ID(RFGUIDE_SHEET6_TITLE4),
	WINDOW_ID(RFGUIDE_SHEET6_TITLE5),
	WINDOW_ID(RFGUIDE_SHEET6_TITLE6),
	WINDOW_ID(RFGUIDE_SHEET6_TITLE7),
	WINDOW_ID(RFGUIDE_SHEET6_TITLE8),
	WINDOW_ID(RFGUIDE_SHEET6_TITLE9),
	WINDOW_ID(RFGUIDE_SHEET6_TITLE10),

	WINDOW_ID(RFGUIDE_SHEET6_DESC1),
	WINDOW_ID(RFGUIDE_SHEET6_DESC2),
	WINDOW_ID(RFGUIDE_SHEET6_DESC3),
	WINDOW_ID(RFGUIDE_SHEET6_DESC4),
	WINDOW_ID(RFGUIDE_SHEET6_DESC5),
	WINDOW_ID(RFGUIDE_SHEET6_DESC6),
	WINDOW_ID(RFGUIDE_SHEET6_DESC7),
	WINDOW_ID(RFGUIDE_SHEET6_DESC8),
	WINDOW_ID(RFGUIDE_SHEET6_DESC9),
	WINDOW_ID(RFGUIDE_SHEET6_DESC10),

	WINDOW_ID(RFGUIDE_SHEET7_TITLE1),
	WINDOW_ID(RFGUIDE_SHEET7_TITLE2),
	WINDOW_ID(RFGUIDE_SHEET7_TITLE3),
	WINDOW_ID(RFGUIDE_SHEET7_TITLE4),
	WINDOW_ID(RFGUIDE_SHEET7_TITLE5),
	WINDOW_ID(RFGUIDE_SHEET7_TITLE6),
	WINDOW_ID(RFGUIDE_SHEET7_TITLE7),
	WINDOW_ID(RFGUIDE_SHEET7_TITLE8),
	WINDOW_ID(RFGUIDE_SHEET7_TITLE9),
	WINDOW_ID(RFGUIDE_SHEET7_TITLE10),

	WINDOW_ID(RFGUIDE_SHEET7_DESC1),
	WINDOW_ID(RFGUIDE_SHEET7_DESC2),
	WINDOW_ID(RFGUIDE_SHEET7_DESC3),
	WINDOW_ID(RFGUIDE_SHEET7_DESC4),
	WINDOW_ID(RFGUIDE_SHEET7_DESC5),
	WINDOW_ID(RFGUIDE_SHEET7_DESC6),
	WINDOW_ID(RFGUIDE_SHEET7_DESC7),
	WINDOW_ID(RFGUIDE_SHEET7_DESC8),
	WINDOW_ID(RFGUIDE_SHEET7_DESC9),
	WINDOW_ID(RFGUIDE_SHEET7_DESC10),

	WINDOW_ID(RFGUIDE_SHEET8_TITLE1),
	WINDOW_ID(RFGUIDE_SHEET8_TITLE2),
	WINDOW_ID(RFGUIDE_SHEET8_TITLE3),
	WINDOW_ID(RFGUIDE_SHEET8_TITLE4),
	WINDOW_ID(RFGUIDE_SHEET8_TITLE5),
	WINDOW_ID(RFGUIDE_SHEET8_TITLE6),
	WINDOW_ID(RFGUIDE_SHEET8_TITLE7),
	WINDOW_ID(RFGUIDE_SHEET8_TITLE8),
	WINDOW_ID(RFGUIDE_SHEET8_TITLE9),
	WINDOW_ID(RFGUIDE_SHEET8_TITLE10),

	WINDOW_ID(RFGUIDE_SHEET8_DESC1),
	WINDOW_ID(RFGUIDE_SHEET8_DESC2),
	WINDOW_ID(RFGUIDE_SHEET8_DESC3),
	WINDOW_ID(RFGUIDE_SHEET8_DESC4),
	WINDOW_ID(RFGUIDE_SHEET8_DESC5),
	WINDOW_ID(RFGUIDE_SHEET8_DESC6),
	WINDOW_ID(RFGUIDE_SHEET8_DESC7),
	WINDOW_ID(RFGUIDE_SHEET8_DESC8),
	WINDOW_ID(RFGUIDE_SHEET8_DESC9),
	WINDOW_ID(RFGUIDE_SHEET8_DESC10),

	WINDOW_ID(RFGUIDE_SHEET9_TITLE1),
	WINDOW_ID(RFGUIDE_SHEET9_TITLE2),
	WINDOW_ID(RFGUIDE_SHEET9_TITLE3),
	WINDOW_ID(RFGUIDE_SHEET9_TITLE4),
	WINDOW_ID(RFGUIDE_SHEET9_TITLE5),
	WINDOW_ID(RFGUIDE_SHEET9_TITLE6),
	WINDOW_ID(RFGUIDE_SHEET9_TITLE7),
	WINDOW_ID(RFGUIDE_SHEET9_TITLE8),
	WINDOW_ID(RFGUIDE_SHEET9_TITLE9),
	WINDOW_ID(RFGUIDE_SHEET9_TITLE10),

	WINDOW_ID(RFGUIDE_SHEET9_DESC1),
	WINDOW_ID(RFGUIDE_SHEET9_DESC2),
	WINDOW_ID(RFGUIDE_SHEET9_DESC3),
	WINDOW_ID(RFGUIDE_SHEET9_DESC4),
	WINDOW_ID(RFGUIDE_SHEET9_DESC5),
	WINDOW_ID(RFGUIDE_SHEET9_DESC6),
	WINDOW_ID(RFGUIDE_SHEET9_DESC7),
	WINDOW_ID(RFGUIDE_SHEET9_DESC8),
	WINDOW_ID(RFGUIDE_SHEET9_DESC9),
	WINDOW_ID(RFGUIDE_SHEET9_DESC10),

	WINDOW_ID(RFGUIDE_SHEET10_TITLE1),
	WINDOW_ID(RFGUIDE_SHEET10_TITLE2),
	WINDOW_ID(RFGUIDE_SHEET10_TITLE3),
	WINDOW_ID(RFGUIDE_SHEET10_TITLE4),
	WINDOW_ID(RFGUIDE_SHEET10_TITLE5),
	WINDOW_ID(RFGUIDE_SHEET10_TITLE6),
	WINDOW_ID(RFGUIDE_SHEET10_TITLE7),
	WINDOW_ID(RFGUIDE_SHEET10_TITLE8),
	WINDOW_ID(RFGUIDE_SHEET10_TITLE9),
	WINDOW_ID(RFGUIDE_SHEET10_TITLE10),

	WINDOW_ID(RFGUIDE_SHEET10_DESC1),
	WINDOW_ID(RFGUIDE_SHEET10_DESC2),
	WINDOW_ID(RFGUIDE_SHEET10_DESC3),
	WINDOW_ID(RFGUIDE_SHEET10_DESC4),
	WINDOW_ID(RFGUIDE_SHEET10_DESC5),
	WINDOW_ID(RFGUIDE_SHEET10_DESC6),
	WINDOW_ID(RFGUIDE_SHEET10_DESC7),
	WINDOW_ID(RFGUIDE_SHEET10_DESC8),
	WINDOW_ID(RFGUIDE_SHEET10_DESC9),
	WINDOW_ID(RFGUIDE_SHEET10_DESC10),
	
	WINDOW_ID(RFGUIDE_OKBTN),
	
	WINDOW_ID(DIS_DISSOLVEDLG),
	WINDOW_ID(DIS_DISSOLVEICONDLG),
	WINDOW_ID(DIS_DISSOLVEICONGRIDDLG),
	WINDOW_ID(DIS_DISSOLVEOKBTN),
	WINDOW_ID(DIS_DISSOLVECANCELBTN),
	WINDOW_ID(DIS_DISSOLVECOST),

	// 080215 LUJ, 옵션 적용 창. ApplyOptionDialog.bin
	WINDOW_ID(APPLY_OPTION_DIALOG),
	WINDOW_ID(APPLY_OPTION_RESULT_STATIC),
	WINDOW_ID(APPLY_OPTION_ICON_DIALOG),
	WINDOW_ID(APPLY_OPTION_SUBMIT_BUTTON),
	WINDOW_ID(APPLY_OPTION_CANCEL_BUTTON),
	
/////////////////////////////////////////////////////////////////////////////////////

/* ⓒoI￠￥I￠￢E */
	WINDOW_ID(MNM_DIALOG),
	WINDOW_ID(MNM_PARTYDISPLAY_ONOFF),
	WINDOW_ID(MNM_TOGGLEFULL),
	WINDOW_ID(MNM_MAPNAME),
	WINDOW_ID(MNM_CHANNELNAME), 
	WINDOW_ID(MNM_POSXY),
	// 070430 LYW --- WindowIDs : Add window id for minimap's toggle button.
	WINDOW_ID(MNM_ONOFF), 
/*BigMapDlg*/
	WINDOW_ID(BM_DIALOG),
	
/* ￠￢￠O￠?i¨o¨￢ */
	WINDOW_ID(INT_MOUSEBASIC),
	WINDOW_ID(INT_MOUSECLICK),

	//￠￢o¨o¨￢AI ¡ÆOAIAo A¡E
	WINDOW_ID(CG_MONSTERGUAGEDLG),

	// 070123 LYW --- Add window id for target dialog.
	WINDOW_ID(CG_MONSTERRACE), 
	WINDOW_ID(CG_NPCRACE), 
	WINDOW_ID(CG_PLAYERRACE), 

	WINDOW_ID(CG_MONSTERGUAGENAME),

	// 070123 LYW --- Delete this id.
	//WINDOW_ID(CG_MONSTERGUAGELIFETEXT),

	WINDOW_ID(CG_MONSTERGUAGELIFE),
	WINDOW_ID(CG_GUILDNAME),
	WINDOW_ID(CG_GUILDUNION_NAME),
	WINDOW_ID(CG_GUILDUNION_BASE),
	// 070123 LYW --- Delete these id.
	//WINDOW_ID(CG_GUILDUNION_BTN),
	//WINDOW_ID(CG_UNIONNAME),

	// 06. 01. 타겟팅창 인터페이스 변경 - 이영준
	WINDOW_ID(CG_NPCNAME),

	// 070123 LYW --- Add window id for npc occupation.
	WINDOW_ID(CG_NPCOCCUPATION),

	// 070123 LYW --- Delete this id.
	//WINDOW_ID(CG_MONSTERGUAGELIFEBASE),

	// 070109 LYW --- Add window id for target window.
	WINDOW_ID( TG_MENUBOX ), 
	WINDOW_ID( CG_LIFEIMAGE ),
	WINDOW_ID( CG_CRTGUAGELIFE ),
	WINDOW_ID( CG_CRTLIFE ),

	// 070123 LYW --- Add window id for character name.
	WINDOW_ID( CG_CRTGUAGENAME ), 
	WINDOW_ID(CG_PETMASTERNAME),
	WINDOW_ID(CG_PETNAME),
	// 070109 LYW --- Add window id for popup window.
	WINDOW_ID( CG_ST_BACK_TOP ),
	WINDOW_ID( CG_ST_BACK_MIDDLE1 ), 
	WINDOW_ID( CG_ST_BACK_MIDDLE2 ), 
	WINDOW_ID( CG_ST_BACK_MIDDLE3 ), 
	WINDOW_ID( CG_ST_BACK_BOTTOM ),
	WINDOW_ID( CG_BT_MENU_BUTTON1 ), 
	WINDOW_ID( CG_BT_MENU_BUTTON2 ), 
	WINDOW_ID( CG_BT_MENU_BUTTON3 ), 
	WINDOW_ID( CG_BT_MENU_BUTTON4 ), 
	WINDOW_ID( CG_BT_MENU_BUTTON5 ), 

/*MenuSlotDialog*/
	WINDOW_ID(MSI_DLG),
	WINDOW_ID(MSI_PREVPAGEBTN),
	WINDOW_ID(MSI_NEXTPAGEBTN),
	WINDOW_ID(MSI_PAGESHEET1),
	WINDOW_ID(MSI_PAGESHEET2),
	WINDOW_ID(MSI_PAGESHEET3),
	WINDOW_ID(MSI_PAGESHEET4),

/*EventNotifyDialog*/
	WINDOW_ID(GMOT_OPENTALKDLG),
	WINDOW_ID(GMOT_STC_TITLE),
	WINDOW_ID(GMOT_TA_CONTEXT),

/*MallNoticeDialog*/
	WINDOW_ID(ITEM_MALLDLG),
	WINDOW_ID(ITEM_TABBTN1),
	WINDOW_ID(ITEM_TABBTN2),
	WINDOW_ID(ITEM_SHEET1),
	WINDOW_ID(ITEM_SHEET2),
	WINDOW_ID(ITEM_MALLBTN),

//////////////
//---Murim Net
//---playroom
	WINDOW_ID(MNPRI_DIALOG),
	WINDOW_ID(MNPRI_LSTDLG_TEAMA),
	WINDOW_ID(MNPRI_LSTDLG_TEAMB),
	WINDOW_ID(MNPRI_LSTDLG_OB),
	WINDOW_ID(MNPRI_BTN_TEAMA),
	WINDOW_ID(MNPRI_BTN_TEAMB),
	WINDOW_ID(MNPRI_BTN_OB),
	WINDOW_ID(MNPRI_STC_TEAMACOUNT),
	WINDOW_ID(MNPRI_STC_OBCOUNT),
	WINDOW_ID(MNPRI_STC_TEAMBCOUNT),
	WINDOW_ID(MNPRI_BTN_MOVETOA),
	WINDOW_ID(MNPRI_BTN_MOVETOOB),
	WINDOW_ID(MNPRI_BTN_MOVETOB),
	WINDOW_ID(MNPRI_LSTDLG_CHAT),
	WINDOW_ID(MNPRI_EB_CHAT),
	WINDOW_ID(MNPRI_PB_CHATTOWHOLE),
	WINDOW_ID(MNPRI_PB_CHATTOTEAM),
	WINDOW_ID(MNPRI_PB_WHISPER),
	WINDOW_ID(MNPRI_STC_TITLE),
	WINDOW_ID(MNPRI_STC_GAMEKIND),
	WINDOW_ID(MNPRI_STC_MAXPLAYER),
	WINDOW_ID(MNPRI_STC_ROOMKIND),
	WINDOW_ID(MNPRI_STC_REPAY),
	WINDOW_ID(MNPRI_BTN_INVITE),
	WINDOW_ID(MNPRI_BTN_BAN),
	WINDOW_ID(MNPRI_BTN_START),
	WINDOW_ID(MNPRI_BTN_EXIT),
//--- murimnet channel	
	WINDOW_ID(MNCNL_DIALOG),
	WINDOW_ID(MNCNL_LSTDLG_IDLIST),
	WINDOW_ID(MNCNL_LSTDLG_PLAYROOMLIST),
	WINDOW_ID(MNCNL_LSTDLG_CHANNELLIST),
	WINDOW_ID(MNCNL_LSTDLG_CHAT),
	WINDOW_ID(MNCNL_EB_CHAT),
	WINDOW_ID(MNCNL_PB_CHATTOWHOLE),
	WINDOW_ID(MNCNL_PB_CHATTOTEAM),
	WINDOW_ID(MNCNL_PB_WHISPER),
	WINDOW_ID(MNCNL_STC_TITLE),
	WINDOW_ID(MNCNL_STC_GAMEKIND),
	WINDOW_ID(MNCNL_STC_MAPNAME),
	WINDOW_ID(MNCNL_STC_MAXPLAYER),
	WINDOW_ID(MNCNL_STC_ROOMKIND),
	WINDOW_ID(MNCNL_STC_REPAY),
	WINDOW_ID(MNCNL_STC_CAPTAIN),
	WINDOW_ID(MNCNL_BTN_EXIT),
	WINDOW_ID(MNCNL_BTN_CREATE),
	WINDOW_ID(MNCNL_BTN_JOIN),
	WINDOW_ID(MNCNL_BTN_IDLIST),		//	id->channel->playroom ¨uⓒª¨u¡ⓒ￠￢| AoA¡Æ¨oA￠?A.
	WINDOW_ID(MNCNL_BTN_CHANNELLIST),	//
	WINDOW_ID(MNCNL_BTN_PLAYROOMLIST),	//
	
//---Murim Net End
//////////////////

/* A￠´ⓒøI */
	WINDOW_ID(CHA_CHANNELDLG),
	WINDOW_ID(CHA_CHANNELLIST),
	WINDOW_ID(CHA_CONNNECTOK),
	WINDOW_ID(CHA_CONNNECTCANCEL),

// ServerList
	WINDOW_ID(SL_SERVERLISTDLG),
	WINDOW_ID(SL_LISTCTRL),
	WINDOW_ID(SL_BTN_CONNECT),
	WINDOW_ID(SL_BTN_EXIT),	
	// 061227 LYW --- Add id for static to use background image of scroll bar.
	WINDOW_ID(SL_ST_SCROLLBGI), 

/* Co¡io¡¾Y NPC */
	WINDOW_ID(WANTNPC_DLG),
	WINDOW_ID(WANTNPC_WANTLCTRL),
	WINDOW_ID(WANTNPC_BUYPRICE),	
	WINDOW_ID(WANTNPC_MYWANTBTN),
	WINDOW_ID(WANTNPC_MYWANTSEARCHBTN),
	WINDOW_ID(WANTNPC_SORTBTN),
	WINDOW_ID(WANTNPC_LISTORDERCOMBOBOX),
	WINDOW_ID(WANTNPC_PMLISTORDERCOMBOBOX),
	WINDOW_ID(WANTNPC_BUYNPCBTN),
	WINDOW_ID(WANTNPC_BUYSEARCHBTN),
	WINDOW_ID(WANTNPC_SEARCHMODEBTN),
	WINDOW_ID(WANTNPC_SEARCHBTN),
	WINDOW_ID(WANTNPC_SEARCHEDIT),
	WINDOW_ID(WANTNPC_GIVEUPBTN),
	WINDOW_ID(WANTNPC_MYSTC),
	WINDOW_ID(WANTNPC_FRONTLISTBTN),
	WINDOW_ID(WANTNPC_1LISTBTN),
	WINDOW_ID(WANTNPC_2LISTBTN),
	WINDOW_ID(WANTNPC_3LISTBTN),
	WINDOW_ID(WANTNPC_4LISTBTN),
	WINDOW_ID(WANTNPC_5LISTBTN),
	WINDOW_ID(WANTNPC_BACKLISTBTN),
	WINDOW_ID(WANTNPC_MYFRONTLISTBTN),
	WINDOW_ID(WANTNPC_MY1LISTBTN),
	WINDOW_ID(WANTNPC_MY2LISTBTN),
	WINDOW_ID(WANTNPC_MY3LISTBTN),
	WINDOW_ID(WANTNPC_MY4LISTBTN),
	WINDOW_ID(WANTNPC_MY5LISTBTN),
	WINDOW_ID(WANTNPC_MYBACKLISTBTN),
	WINDOW_ID(WANTNPC_SEARCHFRONTLISTBTN),
	WINDOW_ID(WANTNPC_SEARCH1LISTBTN),
	WINDOW_ID(WANTNPC_SEARCH2LISTBTN),
	WINDOW_ID(WANTNPC_SEARCH3LISTBTN),
	WINDOW_ID(WANTNPC_SEARCH4LISTBTN),
	WINDOW_ID(WANTNPC_SEARCH5LISTBTN),
	WINDOW_ID(WANTNPC_SEARCHBACKLISTBTN),
	
	/* Co¡io¡¾Y ￥ii¡¤I */
	WINDOW_ID(WANTREG_DLG),
	WINDOW_ID(WANTREG_WANTEDNAME),
	WINDOW_ID(WANTREG_PRIZEEDIT),
	WINDOW_ID(WANTREG_OK),
	WINDOW_ID(WANTREG_CANCEL),
	
	/* Au¨o¨￢¨¡￠c */
	WINDOW_ID(QUE_TOTALDLG),

		/*WINDOW_ID(QUE_QUESTBTN),
		WINDOW_ID(QUE_WANTEDBTN),
		WINDOW_ID(QUE_JOURNALBTN),*/

		WINDOW_ID(QUE_QUESTDLG),
			WINDOW_ID(QUE_PAGE1BTN),
			WINDOW_ID(QUE_PAGE2BTN),
			WINDOW_ID(QUE_PAGE3BTN),
			WINDOW_ID(QUE_PAGE4BTN),
			WINDOW_ID(QUE_PAGE5BTN),

			// 070125 LYW --- Quest : Add window id for page6 button.
			WINDOW_ID(QUE_PAGE6BTN), 

			WINDOW_ID(QUE_ITEM_GRID),
			WINDOW_ID(QUE_QUESTLIST),
			WINDOW_ID(QUE_TITLEBTN),

			WINDOW_ID(QUE_NOTICEBTN), 
			WINDOW_ID(QUE_GIVEUPBTN), 

			WINDOW_ID(QUE_COUNTSTATIC), 

			WINDOW_ID(QUE_DESCDLG),
			WINDOW_ID(QUE_REQUITAL_GOLD), 
			WINDOW_ID(QUE_REQUITAL_EXP), 
			WINDOW_ID(QUE_REQUITAL_GRID),

			WINDOW_ID(QUE_QUICKVIEWDLG),
			//WINDOW_ID(QUE_QUICKVIEWTITLE), 
			WINDOW_ID(QUE_QUICKVIEWLIST),

			WINDOW_ID(GAMENOTIFY_DLG), 
			WINDOW_ID(GAMENOTIFY_LISTDLG), 

		/*WINDOW_ID(QUE_WANTEDDLG),
			WINDOW_ID(QUE_WANTEDLDLG),

		WINDOW_ID(QUE_JOURNALDLG),
			WINDOW_ID(QUE_JOURNALLISTDLG),
			WINDOW_ID(QUE_JOURNALTEXTAREA),
			WINDOW_ID(QUE_JOURNALFRONTBTN),
			WINDOW_ID(QUE_JOURNALBACKBTN),
			WINDOW_ID(QUE_JOURNALPAGE1BTN),
			WINDOW_ID(QUE_JOURNALPAGE2BTN),
			WINDOW_ID(QUE_JOURNALPAGE3BTN),
			WINDOW_ID(QUE_JOURNALPAGE4BTN),
			WINDOW_ID(QUE_JOURNALPAGE5BTN),
			WINDOW_ID(QUE_JOURNALCHECKBOX1BTN),
			WINDOW_ID(QUE_JOURNALCHECKBOX2BTN),
			WINDOW_ID(QUE_JOURNALCHECKBOX3BTN),
			WINDOW_ID(QUE_JOURNALCHECKBOX4BTN),
			WINDOW_ID(QUE_JOURNALCHECKBOX5BTN),			
			WINDOW_ID(QUE_JOURNALSAVE),
			WINDOW_ID(QUE_JOURNALSAVEDLIST),*/

	/*수련장*/
	//등록
	WINDOW_ID(MP_REGISTDLG),
	WINDOW_ID(MP_RSKILLICON),
	WINDOW_ID(MP_RSKILLINFO),
	WINDOW_ID(MP_RPRACTICEINFO),
	WINDOW_ID(MP_RFEE),
	WINDOW_ID(MP_ROKBTN),
	WINDOW_ID(MP_RCANCELBTN),
	//미션
	WINDOW_ID(MP_MISSIONDLG),
	WINDOW_ID(MP_MMISSION),
	WINDOW_ID(MP_MCAUTION),
	//회복 설명
	WINDOW_ID(MP_NOTICEDLG),
	WINDOW_ID(MP_NCAUTION),
	WINDOW_ID(MP_NREDCAUTION),
	//게이지바
	WINDOW_ID(MP_GUAGEDLG),
	WINDOW_ID(MP_GEXPGUAGE),
	WINDOW_ID(MP_GTIME),
	WINDOW_ID(MP_GEXPERCENT),
	WINDOW_ID(MP_TITLE),




////////////	
// PKLOOTING
	WINDOW_ID(PLI_IGD_ITEM),
	WINDOW_ID(PLI_STC_BADFAME),
	WINDOW_ID(PLI_STC_TIME),
	WINDOW_ID(PLI_STC_CHANCE),
	WINDOW_ID(PLI_STC_TARGETNAME),
	WINDOW_ID(PLI_STC_ITEM),
	WINDOW_ID(PLI_BTN_CLOSE),
	WINDOW_ID(PLI_STC_END),
	WINDOW_ID(PLI_STC_NONE),
	
//////////////
// BAIL
	WINDOW_ID(BAIL_DLG),
	WINDOW_ID(BAIL_TEXTAREA),
	WINDOW_ID(BAIL_OK),
	WINDOW_ID(BAIL_CANCEL),
	WINDOW_ID(BAIL_BAILEDITBOX),	

////////////////
// CHINA ADVICE
	WINDOW_ID(CNA_CNADVICEDLG),
	WINDOW_ID(CNA_TEXTAREA),
	WINDOW_ID(CNA_BTN_OK),
	
///////////////////
// ITEM DISSOLUTION
	WINDOW_ID(DIS_DISSOLUTIONDLG),
	WINDOW_ID(DIS_BASEICONDLG),
	WINDOW_ID(DIS_NUMBTN1),
	WINDOW_ID(DIS_NUMBTN2),
	WINDOW_ID(DIS_NUMBTN3),
	WINDOW_ID(DIS_ICONGRIDDLG1),
	WINDOW_ID(DIS_ICONGRIDDLG2),
	WINDOW_ID(DIS_ICONGRIDDLG3),
	WINDOW_ID(DIS_OKBTN),
	WINDOW_ID(DIS_CANCELBTN),
	
////////////////////
// SHOPITEM
	WINDOW_ID(ITMALL_BASEDLG),
		WINDOW_ID(ITMALL_GRID),
//		WINDOW_ID(ITMALL_GRID1),
//		WINDOW_ID(ITMALL_GRID2),
//		WINDOW_ID(ITMALL_GRID3),
//		WINDOW_ID(ITMALL_BTN1),
//		WINDOW_ID(ITMALL_BTN2),
//		WINDOW_ID(ITMALL_BTN3),

////////////////////
// MOVEDIALOG
	WINDOW_ID(SA_MOVEDLG),
		WINDOW_ID(SA_MOVELIST),
		WINDOW_ID(SA_CHANGNAME),
		WINDOW_ID(SA_MOVEOK),
		WINDOW_ID(SA_MOVEDEL),
		WINDOW_ID(SA_MOVETABBTN1),
		WINDOW_ID(SA_MOVETABBTN2),		

////////////////////
// SAVEPOINTDIALOG
	WINDOW_ID(CHA_NAMEDLG),
		WINDOW_ID(CHA_NAMEEDITBOX),
		WINDOW_ID(CHA_NAME_OKBTN),
		WINDOW_ID(CHA_NAME_CANCELBTN),

//------- guildfieldwar
	WINDOW_ID(GFW_DECLAREDLG),
		WINDOW_ID(GFW_DECLARE_MSG),
		WINDOW_ID(GFW_DECLARE_EDITBOX),
		WINDOW_ID(GFW_MONEY_EDITBOX),
		WINDOW_ID(GFW_MONEY_MSG1),
		WINDOW_ID(GFW_MONEY_MSG2),
		WINDOW_ID(GFW_MONEY_MSG3),
		WINDOW_ID(GFW_MONEY_CHK),
		WINDOW_ID(GFW_MONEY_STATIC),
		WINDOW_ID(GFW_DECLARE_OKBTN),
		WINDOW_ID(GFW_DECLARE_CANCELBTN),
	WINDOW_ID(GFW_RESULTDLG),
		WINDOW_ID(GFW_RESULT_TITILE),
		WINDOW_ID(GFW_RESULT_MSG),
		WINDOW_ID(GFW_RESULT_0),
		WINDOW_ID(GFW_RESULT_1),
		WINDOW_ID(GFW_RESULT_2),
		WINDOW_ID(GFW_RESULT_3),
		WINDOW_ID(GFW_RESULT_4),
		WINDOW_ID(GFW_RESULT_5),
		WINDOW_ID(GFW_RESULT_OKBTN),
		WINDOW_ID(GFW_RESULT_CANCELBTN),
		WINDOW_ID(GFW_RESULT_CONFIRMBTN),
		WINDOW_ID(GFW_MY_GUILD_NAME),
		WINDOW_ID(GFW_MY_GUILD_LEVEL),
		WINDOW_ID(GFW_MY_GUILD_MASTER),
		WINDOW_ID(GFW_MY_GUILD_MONEY),
	WINDOW_ID(GFW_INFODLG),
		WINDOW_ID(GFW_INFO_TITLE),
		WINDOW_ID(GFW_INFO_MSG),
		WINDOW_ID(GFW_INFO_LIST),
		WINDOW_ID(GFW_INFO_TEXT),
		WINDOW_ID(GFW_INFO_STATIC_0),
		WINDOW_ID(GFW_INFO_STATIC_1),
		WINDOW_ID(GFW_INFO_STATIC_2),
		WINDOW_ID(GFW_INFO_SUGGEST_OKBTN),
		WINDOW_ID(GFW_INFO_SURREND_OKBTN),
		WINDOW_ID(GFW_GDU_REMOVE_OKBTN),
		WINDOW_ID(GFW_INFO_CANCELBTN),
	WINDOW_ID(GW_INFODLG),
		WINDOW_ID(GW_BLACKLIST),
		WINDOW_ID(GW_WHITELIST),
		WINDOW_ID(GW_INFOSTATIC),
		WINDOW_ID(GW_INFOCLOSEBTN),
	
///////////////////
// SkillPointRedistibute
	WINDOW_ID(SK_POINTDLG),
		WINDOW_ID(SK_POINTAGAIN1BTN),
		WINDOW_ID(SK_POINTAGAIN2BTN),
		WINDOW_ID(SK_POINTAGAIN3BTN),
		WINDOW_ID(SK_ICONGRID1),
		WINDOW_ID(SK_ICONGRID2),
		WINDOW_ID(SK_ICONGRID3),
		WINDOW_ID(SK_POINTSTATIC),
		WINDOW_ID(SK_USESTATIC),
		WINDOW_ID(SK_ORIGINALSTATIC),
		WINDOW_ID(SK_UPBTN),
		WINDOW_ID(SK_DOWNBTN),
		WINDOW_ID(SK_OKBTN),

////////////////////
// SkillPointNotify
	WINDOW_ID(SK_POINTNOTIFYDLG),
		WINDOW_ID(SK_INFOTEXT1),
		WINDOW_ID(SK_INFOTEXT2),
		WINDOW_ID(SK_STARTBTN),

// partywar
	WINDOW_ID(PW_DLG),
		WINDOW_ID(PW_BTN_LOCK),
		WINDOW_ID(PW_BTN_UNLOCK),
		WINDOW_ID(PW_BTN_START),
		WINDOW_ID(PW_BTN_CANCEL),
		WINDOW_ID(PW_TITLE),
		WINDOW_ID(PW_TEAM1),
		WINDOW_ID(PW_TEAM2),
		WINDOW_ID(PW_TIME),
		WINDOW_ID(PW_CB_MEMBER0),
		WINDOW_ID(PW_CB_MEMBER1),
		WINDOW_ID(PW_CB_MEMBER2),
		WINDOW_ID(PW_CB_MEMBER3),
		WINDOW_ID(PW_CB_MEMBER4),
		WINDOW_ID(PW_CB_MEMBER5),
		WINDOW_ID(PW_CB_MEMBER6),
		WINDOW_ID(PW_CB_MEMBER7),
		WINDOW_ID(PW_CB_MEMBER8),
		WINDOW_ID(PW_CB_MEMBER9),
		WINDOW_ID(PW_CB_MEMBER10),
		WINDOW_ID(PW_CB_MEMBER11),
		WINDOW_ID(PW_CB_MEMBER12),
		WINDOW_ID(PW_CB_MEMBER13),
		WINDOW_ID(PW_MEMBER0),
		WINDOW_ID(PW_MEMBER1),
		WINDOW_ID(PW_MEMBER2),
		WINDOW_ID(PW_MEMBER3),
		WINDOW_ID(PW_MEMBER4),
		WINDOW_ID(PW_MEMBER5),
		WINDOW_ID(PW_MEMBER6),
		WINDOW_ID(PW_MEMBER7),
		WINDOW_ID(PW_MEMBER8),
		WINDOW_ID(PW_MEMBER9),
		WINDOW_ID(PW_MEMBER10),
		WINDOW_ID(PW_MEMBER11),
		WINDOW_ID(PW_MEMBER12),
		WINDOW_ID(PW_MEMBER13),


	// 외치기
	WINDOW_ID(CHA_CREATEDLG),
	WINDOW_ID(CHA_MSG),
	WINDOW_ID(CHA_CREATEOKBTN),
	// 061204 LYW --- Delete Preexistence Chatting Dialog.
	/*
	WINDOW_ID(CHA_DLG),
	WINDOW_ID(CHA_LIST),
	*/

	//
	WINDOW_ID(SEE_CHASEDLG),
		WINDOW_ID(SEE_CHASE_MSG),
		WINDOW_ID(SEE_CHASE_MAP),
		WINDOW_ID(CHASE_SEEOKBTN),
	WINDOW_ID(CHASEDLG),
		WINDOW_ID(CHASE_EDITBOX),
		WINDOW_ID(CHASE_OKBTN),
		WINDOW_ID(CHASE_CANCELBTN),

	//
	WINDOW_ID(CH_NAME_CHANGE_DLG),
		WINDOW_ID(CH_NAME_CHANGE_EDITBOX),
		WINDOW_ID(CH_NAME_CHANGE_OKBTN),
		WINDOW_ID(CH_NAME_CHANGE_CANCELBTN),		

	WINDOW_ID(CH_NAME_CHANGE_OPDLG),
		WINDOW_ID(CH_NAME_CHANGE_STARTBTN),


	// Guild Tournament
	WINDOW_ID(GDT_ENTRYDLG),
		WINDOW_ID(GDT_ENTRY1),		
		WINDOW_ID(GDT_ENTRY2),
		WINDOW_ID(GDT_ENTRYBTN),


	WINDOW_ID(GDT_ENTRYCANCELDLG),
		WINDOW_ID(GDT_CANCELBTN),


	WINDOW_ID(GDT_DLG),
		WINDOW_ID(GDT_MAIN1),
		WINDOW_ID(GDT_MAIN2),
		WINDOW_ID(GDT_SEMIFINAL_PUSHUPBTN),
		WINDOW_ID(GDT_AGROUP_PUSHUPBTN),
		WINDOW_ID(GDT_BGROUP_PUSHUPBTN),
		WINDOW_ID(GDT_CGROUP_PUSHUPBTN),
		WINDOW_ID(GDT_DGROUP_PUSHUPBTN),

		WINDOW_ID(GDT_MAINMARK0),				// 본선
		WINDOW_ID(GDT_MAINMARK1),
		WINDOW_ID(GDT_MAINMARK2),
		WINDOW_ID(GDT_MAINMARK3),
		WINDOW_ID(GDT_MAINMARK4),
		WINDOW_ID(GDT_MAINMENBER1),
		WINDOW_ID(GDT_MAINMENBER2),
		WINDOW_ID(GDT_MAINMENBER3),
		WINDOW_ID(GDT_MAINMENBER4),

		WINDOW_ID(GDT_SECONDMARK0),				// 예선
		WINDOW_ID(GDT_SECONDMARK1),
		WINDOW_ID(GDT_SECONDMARK2),
		WINDOW_ID(GDT_SECONDMARK3),
		WINDOW_ID(GDT_SECONDMARK4),
		WINDOW_ID(GDT_SECONDMARK5),
		WINDOW_ID(GDT_SECONDMARK6),
		WINDOW_ID(GDT_SECONDMARK7),
		WINDOW_ID(GDT_SECONDMARK8),
		WINDOW_ID(GDT_SECONDMEMBER1),
		WINDOW_ID(GDT_SECONDMEMBER2),
		WINDOW_ID(GDT_SECONDMEMBER3),
		WINDOW_ID(GDT_SECONDMEMBER4),
		WINDOW_ID(GDT_SECONDMEMBER5),
		WINDOW_ID(GDT_SECONDMEMBER6),
		WINDOW_ID(GDT_SECONDMEMBER7),
		WINDOW_ID(GDT_SECONDMEMBER8),
		
		WINDOW_ID(GDT_LINE1),				// Line Static
		WINDOW_ID(GDT_LINE2),
		WINDOW_ID(GDT_LINE3),
		WINDOW_ID(GDT_LINE4),
		WINDOW_ID(GDT_LINE5),
		WINDOW_ID(GDT_LINE6),
		WINDOW_ID(GDT_LINE7),
		WINDOW_ID(GDT_LINE8),
		WINDOW_ID(GDT_LINE9),
		WINDOW_ID(GDT_LINE10),
		WINDOW_ID(GDT_LINE11),
		WINDOW_ID(GDT_LINE12),
		WINDOW_ID(GDT_LINE13),
		WINDOW_ID(GDT_LINE14),
		WINDOW_ID(GDT_LINE15),
		WINDOW_ID(GDT_LINE16),
		WINDOW_ID(GDT_LINE17),
		WINDOW_ID(GDT_LINE18),
		WINDOW_ID(GDT_LINE19),
		WINDOW_ID(GDT_LINE20),
		WINDOW_ID(GDT_LINE21),
		WINDOW_ID(GDT_LINE22),
		WINDOW_ID(GDT_LINE23),
		WINDOW_ID(GDT_LINE24),
		WINDOW_ID(GDT_LINE25),
		WINDOW_ID(GDT_LINE26),
		WINDOW_ID(GDT_LINE27),
		WINDOW_ID(GDT_LINE28),
		WINDOW_ID(GDT_LINE29),


	WINDOW_ID(GDT_VIEWDLG),
		WINDOW_ID(GDT_BATTLELIST),
		WINDOW_ID(GDT_WARVIEWBTN),
		WINDOW_ID(GDT_VIEWCANCELBTN),
		

	WINDOW_ID(GDT_COUNTDLG),
		WINDOW_ID(GDT_GTIME),
		WINDOW_ID(GDT_OUTBTN),
		WINDOW_ID(GDT_GUILDNAME1),
		WINDOW_ID(GDT_GUILDMEMBER1),
		WINDOW_ID(GDT_GUILDNAME2),
		WINDOW_ID(GDT_GUILDMEMBER2),
		
	// seigewar
	WINDOW_ID(SW_TIMEREGDLG),
		WINDOW_ID(SW_TIMEREG_TEXT),
		WINDOW_ID(SW_TIME_YEAR),
		WINDOW_ID(SW_TIME_MON),
		WINDOW_ID(SW_TIME_DAY),
		WINDOW_ID(SW_TIME_HOUR),
		WINDOW_ID(SW_TIMEREG_OKBTN),
	WINDOW_ID(SW_PROTECTREGDLG),
		WINDOW_ID(SW_PROTECTREG_LIST),
		WINDOW_ID(SW_PROTECTREG_OKBTN),
	WINDOW_ID(SW_INFODLG),
		WINDOW_ID(SW_DEFENSE_LIST),
		WINDOW_ID(SW_OFFENSE_LIST),
		WINDOW_ID(SW_INFOCLOSEBTN),
	WINDOW_ID(SW_PROFITDLG),
		WINDOW_ID(SW_BACIS_TAX),
		WINDOW_ID(SW_CHANGE_TAX),
		WINDOW_ID(SW_BACIS_MONEY),
		WINDOW_ID(SW_OUT_MONEY),
		WINDOW_ID(SW_TAXCHANGE_OKBTN),
		WINDOW_ID(SW_PROFIT_OKBTN),		
		WINDOW_ID(SW_PROFIT_CANCELBTN),	
	WINDOW_ID(ENGRAVEDLG),
		WINDOW_ID(SW_ENGRAVEGUAGE),
		WINDOW_ID(SW_ENGRAVETIME),
		WINDOW_ID(SW_ENGRAVECANCEL),

	WINDOW_ID(SW_COUNTDLG),
		WINDOW_ID(SW_TIME),
		WINDOW_ID(SWTIME_MUNPA),
		
	WINDOW_ID(SW_STARTTIMEDLG),
		WINDOW_ID(SW_STARTTIME),
		WINDOW_ID(SW_REGTIMESTART),
		WINDOW_ID(SW_REGTIMEEND),
		WINDOW_ID(SW_ADMITTIMESTART),
		WINDOW_ID(SW_ADMITTIMEEND),	
		WINDOW_ID(SW_STARTTIME_OKBTN),
	
	//
	WINDOW_ID(ITEM_LOCKDLG),
		WINDOW_ID(IT_LOCKICON),
		WINDOW_ID(IT_LOCKOKBTN),
		WINDOW_ID(IT_LOCKCANCERBTN),
	
		
	//
	WINDOW_ID(CHANGEJOBDLG),
		WINDOW_ID(CJOB_OKBTN),
		WINDOW_ID(CJOB_CANCELBTN),

	// 강화초기화
	WINDOW_ID(RF_DefaultDLG),
		WINDOW_ID(RF_DefaultICON),
		WINDOW_ID(RF_DefaultOKBTN),
		WINDOW_ID(RF_DefaultCANCERBTN),

	// 축복의 돌
	WINDOW_ID(RareCreateDLG),
		WINDOW_ID(RareCreate_ICON),
		WINDOW_ID(RareCreate_OKBTN),
		WINDOW_ID(RareCreate_CANCERBTN),

	WINDOW_ID(KS_DIALOG),

	// 070618 LYW --- WindowIDs : Add window id for close button of key setting tip dialog.
	WINDOW_ID(KS_CLOSEBTN), 

	WINDOW_ID(GUILDNOTE_DLG),
	WINDOW_ID(GN_TEXTREA),
	WINDOW_ID(GN_SENDOKBTN),
	WINDOW_ID(GN_CANCELBTN),

	WINDOW_ID(ALLYNOTE_DLG),
	WINDOW_ID(AN_TEXTREA),
	WINDOW_ID(AN_SENDOKBTN),
	WINDOW_ID(AN_CANCELBTN),

	// 06. 03. 문파공지 - 이영준
	WINDOW_ID(GUILDNOTICE_DLG),
	WINDOW_ID(GNotice_TEXTREA),
	WINDOW_ID(GNotice_SENDOKBTN),
	WINDOW_ID(GNotice_CANCELBTN),

	
	
	//////////////////////////////////////////////////////////////////
	// 06. 06. 2차 전직 - 이영준
	// 무공 변환
	// 변환창
	WINDOW_ID(SkillTransDLG),
	WINDOW_ID(ST_ICON1),
	WINDOW_ID(ST_ICON2),
	WINDOW_ID(SkillTrans_OKBTN),
	WINDOW_ID(SkillTrans_CANCERBTN),
	WINDOW_ID(SkillTrans_ItemView),
	WINDOW_ID(ST_Option1),
	WINDOW_ID(ST_Option2),
	WINDOW_ID(ST_Option3),
	WINDOW_ID(ST_Option4),
	WINDOW_ID(ST_Option5),
	// 초기화창
	WINDOW_ID(T_DefaultDLG),
	WINDOW_ID(T_DefaultICON),
	WINDOW_ID(T_DefaultOKBTN),
	WINDOW_ID(T_DefaultCANCERBTN),

	//SW060713 문하생
	WINDOW_ID(JOIN_OPTIONDLG),
	WINDOW_ID(JO_CANCELBTN),
	WINDOW_ID(JO_MEMBERBTN),
	WINDOW_ID(JO_STUDENTBTN),

	WINDOW_ID(NI_DIALOG),
	// 070328 LYW --- WindowIDs : Add window id for notice static of NpcImage dialog.
	WINDOW_ID(NI_NOTICE), 
	// 070620 LYW --- WindowIDs : Add window id to setting position and scale of top bottom image.
	WINDOW_ID(NI_TOPIMG),  
	WINDOW_ID(NI_BOTTOMIMG),  


	//////////////////////////////////////////////////////////////////////
	// 데이트 매칭	2007/03/16	-	이진영.
	// 두개의 탭을 "DateMatchingDlg.bin"에서 수용한다.
	//WINDOW_ID(DMD_DATEMATCHINGDLG),	// 메인 다이얼로그.
	//	WINDOW_ID(DMD_CLOSEBTN),	// 클로즈 버튼.
	//	// 아래부터는 DateMatchingUpperDlg.bin 의 내용.
	//	WINDOW_ID(DMD_UPPERTAB1),		// 데이트 상대 리스트 탭 버튼.
	//		WINDOW_ID(DMD_AGE_COMBO),				// 나이 콤보박스
	//		WINDOW_ID(DMD_AGE_COMBO_BTN),			// 나이 콤보 버튼.
	//		WINDOW_ID(DMD_REGION_COMBO),			// 접속지역 콤보박스
	//		WINDOW_ID(DMD_REGION_COMBO_BTN),		// 지역 콤보 버튼.
	//		WINDOW_ID(DMD_GENDER_CHECKBOX_MALE),	// 성별 체크박스, 남자
	//		WINDOW_ID(DMD_GENDER_CHECKBOX_FEMALE),	// 성별 체크박스, 여자
	//		WINDOW_ID(DMD_SEARCH_BTN),				// 검색하기 버튼
	//		WINDOW_ID(DMD_SEARCH_LIST),				// 검색 결과 리스트
	//		WINDOW_ID(DMD_REFRESH_BTN),				// 새로고침 버튼
	//		WINDOW_ID(DMD_START_CHAT_BTN),			// 대화하기 버튼
	//	WINDOW_ID(DMD_UPPERTAB2),		// 1:1 채팅 탭 버튼.
	//		WINDOW_ID(DMD_CHAT_WINDOW_LIST),		// 1:1 채팅 대화내용 리스트
	//		WINDOW_ID(DMD_CHAT_EDIT),				// 채팅글 입력창

	//	// 아래부터는 DateMatchingLowerDlg.bin 의 내용.
	//	WINDOW_ID(DMD_LOWERTAB1),		// 내정보 탭 버튼.
	//		WINDOW_ID(DMD_MY_NICKNAME),				// 내 실제 닉네임
	//		WINDOW_ID(DMD_MY_GENDER),				// 내 실제 성별
	//		WINDOW_ID(DMD_MY_AGE),					// 내 실제 나이
	//		WINDOW_ID(DMD_MY_REGION),				// 내 실제 접속지역
	//		WINDOW_ID(DMD_MY_GOOD_FEELING_DEGREE),		// 내 실제 호감도
	//		WINDOW_ID(DMD_MY_GOOD_FEELING_ICONGRID),	// 성향, 호감, 아이콘
	//		WINDOW_ID(DMD_MY_BAD_FEELING_ICONGRID),		// 성향, 비호감, 아이콘
	//		WINDOW_ID(DMD_MY_INTRODUCTION_EDIT),		// 자기 소개
	//		WINDOW_ID(DMD_CHANGE_MY_INTRODUCTION_BTN),	// 소개변경.
	//		WINDOW_ID(DMD_SAVE_MY_INTRODUCTION_BTN),	// 저장하기
	//	WINDOW_ID(DMD_LOWERTAB2),		// 상대정보 탭 버튼.
	//		WINDOW_ID(DMD_PARTNER_NICKNAME),		// 상대 실제 닉네임
	//		WINDOW_ID(DMD_PARTNER_GENDER),			// 상대 실제 성별
	//		WINDOW_ID(DMD_PARTNER_AGE),				// 상대 실제 나이
	//		WINDOW_ID(DMD_PARTNER_REGION),			// 상대 실제 접속지역
	//		WINDOW_ID(DMD_PARTNER_GOOD_FEELING_DEGREE),		// 상대 실제 호감도
	//		WINDOW_ID(DMD_PARTNER_GOOD_FEELING_ICONGRID),	// 성향, 호감, 아이콘
	//		WINDOW_ID(DMD_PARTNER_BAD_FEELING_ICONGRID),	// 성향, 비호감, 아이콘
	//		WINDOW_ID(DMD_PARTNER_INTRODUCTION_EDIT),		// 상대의 자기 소개
	//		WINDOW_ID(DMD_REGIST_PARTNER_BTN),			// 친구등록.
	//		WINDOW_ID(DMD_RECOMMEND_PARTNER_BTN),		// 추천하기.
	//	WINDOW_ID(DMD_LOWERTAB3),		// 데이트 기록 탭.
	//		WINDOW_ID(DMD_DATE_LIST),					// 데이트 기록 리스트.
	//		WINDOW_ID(DMD_SEND_MESSAGE_BTN),			// 쪽지쓰기.

	// 070605 LYW --- WindowIDs : Modified window id of matching dialog.
	WINDOW_ID(DMD_DATEMATCHINGDLG),	// 메인 다이얼로그.

	WINDOW_ID(DMD_PARTNERLISTDLG), 
	WINDOW_ID(DMD_CHATDLG), 
	WINDOW_ID(DMD_MYINFODLG), 
	WINDOW_ID(DMD_PARTNERINFODLG), 
	WINDOW_ID(DMD_RECORDDLG), 

	WINDOW_ID(DMD_UPPERTAB1),
	WINDOW_ID(DMD_UPPERTAB2),

	WINDOW_ID(DMD_LOWERTAB1),
	WINDOW_ID(DMD_LOWERTAB2),
	WINDOW_ID(DMD_LOWERTAB3),

	WINDOW_ID(DMD_AGE_COMBO),				// 나이 콤보박스
	WINDOW_ID(DMD_REGION_COMBO),			// 접속지역 콤보박스
	WINDOW_ID(DMD_GENDER_CHECKBOX_MALE),	// 성별 체크박스, 남자
	WINDOW_ID(DMD_GENDER_CHECKBOX_FEMALE),	// 성별 체크박스, 여자
	WINDOW_ID(DMD_SEARCH_BTN),				// 검색하기 버튼
	WINDOW_ID(DMD_REFRESH_BTN),				// 새로고침 버튼
	WINDOW_ID(DMD_START_CHAT_BTN),			// 대화하기 버튼
	WINDOW_ID(DMD_SEARCH_LIST),				// 검색 결과 리스트
	WINDOW_ID(DMD_LISTSELECT_IMAGE),		// 리스트 선택 이미지
	WINDOW_ID(DMD_LISTOVER_IMAGE),			// 리스트 오버 이미지

	WINDOW_ID(DMD_PREV_BTN), 
	WINDOW_ID(DMD_NEXT_BTN), 
	WINDOW_ID(DMD_PAGE_NUM), 
	WINDOW_ID(DMD_PAGE_SLASH), 
	WINDOW_ID(DMD_PAGE_TOTAL), 
	// desc_hseos_데이트매칭01
	// S 데이트매칭 추가 added by hseos 2007.11.20
	WINDOW_ID(DMD_TITLE),
	WINDOW_ID(DMD_GROUP_PREV_BTN), 
	WINDOW_ID(DMD_GROUP_NEXT_BTN), 
	WINDOW_ID(DMD_GROUP_10PREV_BTN), 
	WINDOW_ID(DMD_GROUP_10NEXT_BTN), 
	WINDOW_ID(DMD_GROUP_NUM), 
	WINDOW_ID(DMD_GROUP_SLASH), 
	WINDOW_ID(DMD_GROUP_TOTAL), 
	// E 데이트매칭 추가 added by hseos 2007.11.20

	// 070607 LYW --- WindowIDs : Add window id to sort result of search box.
	WINDOW_ID(DMD_LIST_BTN_GENDER), 
	WINDOW_ID(DMD_LIST_BTN_AGE), 
	WINDOW_ID(DMD_LIST_BTN_NICKNAME), 
	WINDOW_ID(DMD_LIST_BTN_FAVOR), 
	WINDOW_ID(DMD_LIST_BTN_POINT), 

	WINDOW_ID(DMD_CHAT_WINDOW_LIST), 
	WINDOW_ID(DMD_CHAT_EDIT), 

	WINDOW_ID(DMD_MY_MYFACE),
	WINDOW_ID(DMD_MY_NICKNAME),
	WINDOW_ID(DMD_MY_GENDER),	
	WINDOW_ID(DMD_MY_AGE),
	WINDOW_ID(DMD_MY_REGION),
	WINDOW_ID(DMD_MY_GOOD_FEELING_DEGREE),
	WINDOW_ID(DMD_MY_GOOD_FEELING_ICONGRID),
	WINDOW_ID(DMD_MY_BAD_FEELING_ICONGRID),
	WINDOW_ID(DMD_MY_INTRODUCTION_EDIT),
	WINDOW_ID(DMD_CHANGE_MY_INTRODUCTION_BTN),
	WINDOW_ID(DMD_SAVE_MY_INTRODUCTION_BTN),
	// desc_hseos_데이트 존_01
	// S 데이트 존 추가 added by hseos 2007.11.13	2007.11.15
	WINDOW_ID(DMD_ENTER_DATEZONE_BTN),
	WINDOW_ID(DMD_ENTER_CHALLENGEZONE_BTN),
	// E 데이트 존 추가 added by hseos 2007.11.13	2007.11.15

	WINDOW_ID(DMD_MY_INTRODUCE_UP), 
	WINDOW_ID(DMD_MY_INTRODECE_DOWN), 
	WINDOW_ID(DMD_MY_INTRODECE_GUAGE), 

	WINDOW_ID(DMD_PARTNER_MYFACE),
	WINDOW_ID(DMD_PARTNER_NICKNAME),
	WINDOW_ID(DMD_PARTNER_GENDER),	
	WINDOW_ID(DMD_PARTNER_AGE),
	WINDOW_ID(DMD_PARTNER_REGION),
	WINDOW_ID(DMD_PARTNER_GOOD_FEELING_DEGREE),
	WINDOW_ID(DMD_PARTNER_GOOD_FEELING_ICONGRID),
	WINDOW_ID(DMD_PARTNER_BAD_FEELING_ICONGRID),
	WINDOW_ID(DMD_PARTNER_INTRODUCTION_EDIT),
	WINDOW_ID(DMD_REGIST_PARTNER_BTN),
	WINDOW_ID(DMD_RECOMMEND_PARTNER_BTN),

	WINDOW_ID(DMD_DATE_LIST),
	WINDOW_ID(DMD_SEND_MESSAGE_BTN),
	WINDOW_ID(DMD_RECORD_LIST_NICKNAME), 
	WINDOW_ID(DMD_RECORD_LIST_LASTDATE), 
	WINDOW_ID(DMD_RECORD_LIST_POINT), 

	WINDOW_ID(DMD_CLOSEBTN), 

	// 070605 LYW --- WindowIDs : Add window id for identification dialog.
	WINDOW_ID(DMD_IDENTIFICATIONDLG), 
	WINDOW_ID(DMD_IDT_MYFACE),
	WINDOW_ID(DMD_IDT_NICKNAME),
	WINDOW_ID(DMD_IDT_GENDER),	
	WINDOW_ID(DMD_IDT_AGE),
	WINDOW_ID(DMD_IDT_REGION),
	WINDOW_ID(DMD_IDT_REGIONBTN),
	WINDOW_ID(DMD_IDT_GOOD_FEELING_DEGREE),
	WINDOW_ID(DMD_IDT_GOOD_FEELING_ICONGRID),
	WINDOW_ID(DMD_IDT_BAD_FEELING_ICONGRID),
	WINDOW_ID(DMD_IDT_SAVE_BTN),
	WINDOW_ID(DMD_IDT_CANCEL_BTN),

	// 070605 LYW --- WindowIDs : Add window id for favor icon dialog.
	WINDOW_ID(DMD_FAVOR_ICON_DLG), 
	WINDOW_ID(DMD_FAVOR_ICON), 

	// desc_hseos_데이트 존_01
	// S 데이트 존 추가 added by hseos 2007.11.14  2007.11.15	2008.01.24
	WINDOW_ID(DMD_DATEZONE_MOVELIST_DLG), 
	WINDOW_ID(DMD_DATEZONE_MOVELIST_LISTCTRL), 
	WINDOW_ID(DMD_DATEZONE_MOVELIST_OK), 
	WINDOW_ID(DMD_DATEZONE_MOVELIST_CANCEL), 

	WINDOW_ID(DMD_CHALLENGEZONE_MOVELIST_DLG), 
	WINDOW_ID(DMD_CHALLENGEZONE_MOVELIST_LISTCTRL), 
	WINDOW_ID(DMD_CHALLENGEZONE_MOVELIST_OK), 
	WINDOW_ID(DMD_CHALLENGEZONE_MOVELIST_CANCEL), 

	WINDOW_ID(DMD_CHALLENGEZONE_CLEARNO1_DLG), 
	WINDOW_ID(DMD_CHALLENGEZONE_CLEARNO1_SECTION), 
	WINDOW_ID(DMD_CHALLENGEZONE_CLEARNO1_NAME1), 
	WINDOW_ID(DMD_CHALLENGEZONE_CLEARNO1_NAME2), 
	WINDOW_ID(DMD_CHALLENGEZONE_CLEARNO1_TIME), 
	// E 데이트 존 추가 added by hseos 2007.11.14  2007.11.15	2008.01.24

	/*FAMILY */
	//create
	WINDOW_ID(FD_CREATEDLG),
	WINDOW_ID(FD_CNAME),
	WINDOW_ID(FD_CINTROTEXT),
	WINDOW_ID(FD_CLOCATION),
	WINDOW_ID(FD_CCREATEOKBTN),
	//guild
	WINDOW_ID(FD_GUILDDLG),
	WINDOW_ID(FD_NAME),
	WINDOW_ID(FD_LEVEL),
	WINDOW_ID(FD_MASTER),
	WINDOW_ID(FD_MEMBERNUM),
	WINDOW_ID(FD_LOCATION),
	WINDOW_ID(FD_NAMES),
	WINDOW_ID(FD_LEVELS),
	WINDOW_ID(FD_MASTERS),
	WINDOW_ID(FD_MEMBERNUMS),
	WINDOW_ID(FD_LOCATIONS),
	WINDOW_ID(FD_UNIONNAMES),
	WINDOW_ID(FD_UNIONNAME),
	WINDOW_ID(FD_MEMBERINFOPUSHUPBTN),
	WINDOW_ID(FD_GUILFUNCPUSHUPBTN),
	WINDOW_ID(FD_RELATIONBTN),
	WINDOW_ID(FP_TIME),//Add 060803 by wonju
	WINDOW_ID(FD_MEMBERLIST),
	WINDOW_ID(FD_BANMEMBER),		//m_pGuildBtn[0]
	WINDOW_ID(FD_GIVEMEMBERNICK),
	WINDOW_ID(FD_GIVEMEMBERRANK),
	WINDOW_ID(FD_INVITEMEMBER),
	WINDOW_ID(FD_SECEDE),
	// 06. 03. 문파공지 - 이영준
	WINDOW_ID(FD_NOTICE),
	WINDOW_ID(FD_INVITEUNION),
	WINDOW_ID(FD_SECEDEUNION),
	WINDOW_ID(FD_REMOVEUNION),
	WINDOW_ID(FD_DECLARE),
	WINDOW_ID(FD_SUGGEST),
	WINDOW_ID(FD_SURRENDER),

	//Add 060803 by wonju---------------
	WINDOW_ID(FD_PLUSTIME),
	WINDOW_ID(FD_PLUSTIMESTART),
	WINDOW_ID(FD_POSITION),
	WINDOW_ID(FD_RANK),
	
	//GuildPlusTime - 항목
	WINDOW_ID(FD_POINT),
	WINDOW_ID(FD_PLUSTIMELIST),
	//------------------------------------
		
	//invite
	WINDOW_ID(FD_INVITEDlG),
	WINDOW_ID(FD_IINVITE),
	WINDOW_ID(FD_IOKBTN),
	WINDOW_ID(FD_ICANCELBTN),
	//guild mark
	WINDOW_ID(FDM_MARKREGISTDLG),
	WINDOW_ID(FDM_REGISTOKBTN),
	WINDOW_ID(FDM_NAMEEDIT),
	WINDOW_ID(FDM_INFOTEXT),
	WINDOW_ID(FUM_REGISTOKBTN),
	//guild levelup
	WINDOW_ID(FD_LEVELUPDLG),
	WINDOW_ID(FD_LU1NOTCOMPLETE),
	WINDOW_ID(FD_LU2NOTCOMPLETE),
	WINDOW_ID(FD_LU3NOTCOMPLETE),
	WINDOW_ID(FD_LU4NOTCOMPLETE),
	WINDOW_ID(FD_LU1COMPLETE),
	WINDOW_ID(FD_LU2COMPLETE),
	WINDOW_ID(FD_LU3COMPLETE),
	WINDOW_ID(FD_LU4COMPLETE),
	WINDOW_ID(FD_LUOKBTN),
	WINDOW_ID(FD_LU1),
	WINDOW_ID(FD_LU2),
	WINDOW_ID(FD_LU3),
	WINDOW_ID(FD_LU4),
	WINDOW_ID(FD_LU5),
	//guild nick name 
	WINDOW_ID(FD_NICKNAMEDLG),
	WINDOW_ID(FD_NICKTEXTAREA),
	WINDOW_ID(FD_NICKNAMEEDIT),
	WINDOW_ID(FD_NREGISTOKBTN),	
	//guild change rank
	WINDOW_ID(FDR_RANKDLG),
	WINDOW_ID(FDR_DRANKCOMBOBOX),
	WINDOW_ID(FDR_RANKCOMBOBOX),
	WINDOW_ID(FDR_DOKBTN),
	WINDOW_ID(FDR_OKBTN),
	WINDOW_ID(FDR_MEMBERNAME),	
	//guild warehouse
	WINDOW_ID(FDW_WAREHOUSEDLG),
	WINDOW_ID(FDW_WAREHOUSE1BTN),
	WINDOW_ID(FDW_WAREHOUSE2BTN),
	WINDOW_ID(FDW_TABDLG1),
	WINDOW_ID(FDW_TABDLG2),
	WINDOW_ID(FDW_PUTINMONEYBTN),
	WINDOW_ID(FDW_PUTOUTMONEYBTN),
	WINDOW_ID(FDW_MONEY),
	//guild union
	WINDOW_ID(FDU_CREATEDLG),
		WINDOW_ID(FDU_NAME),
		WINDOW_ID(FDU_TEXT),	
		WINDOW_ID(FDU_OKBTN),

	WINDOW_ID(FAMILYNOTE_DLG),
	WINDOW_ID(FN_TEXTREA),
	WINDOW_ID(FN_SENDOKBTN),
	WINDOW_ID(FN_CANCELBTN),

	// 06. 03. 문파공지 - 이영준
	WINDOW_ID(FAMILYNOTICE_DLG),
	WINDOW_ID(FNotice_TEXTREA),
	WINDOW_ID(FNotice_SENDOKBTN),
	WINDOW_ID(FNotice_CANCELBTN),

	WINDOW_ID(FMY_FAMILYDLG), 

	WINDOW_ID(FMY_NAME), 
	WINDOW_ID(FMY_MASTERNAME), 
	WINDOW_ID(FMY_HONORPOINT), 

	WINDOW_ID(FMY_MEMBERLIST),

	WINDOW_ID(FMY_MEMBERID), 
	WINDOW_ID(FMY_MEMBERLEVEL), 
	WINDOW_ID(FMY_MEMBERCLASS),
	WINDOW_ID(FMY_MEMBERLOGIN), 
	WINDOW_ID(FMY_MEMBERNICKNAME), 
	WINDOW_ID(FMY_MEMBERGUILDNAME), 

	WINDOW_ID(FMY_CHANGENICKNAME), 
	WINDOW_ID(FMY_INVITE), 
	WINDOW_ID(FMY_REGISTMARK), 

	// desc_hseos_패밀리01
	// S 패밀리 추가 added by hseos 2007.10.22
	WINDOW_ID(FMY_LEAVE), 
	WINDOW_ID(FMY_EXPEL), 
	WINDOW_ID(FMY_FARM_MANAGE), 
	// E 패밀리 추가 added by hseos 2007.10.22

	WINDOW_ID(STD_SKILLTREEDLG),
	WINDOW_ID(SKILL_TRAINING),
	WINDOW_ID(SKILL_TRAINLIST),
	WINDOW_ID(SKILL_TRAINGOLD),
	WINDOW_ID(SKILL_TRAINPOINT),
	WINDOW_ID(SKILL_TRAINOK),
	WINDOW_ID(SKILL_TRAINCANCEL),
	WINDOW_ID(SKILL_TRAINTIPLIST),
	WINDOW_ID(SKILL_TRAIN_ICON),
	WINDOW_ID(SKILL_TRAIN_LEVEL ),
	WINDOW_ID(SKILL_TRAIN_SP),
	WINDOW_ID(SKILL_TRAIN_MANA),
	WINDOW_ID(SKILL_TRAIN_GOLD),
	// 080417 LUJ, 길드 스킬때는 텍스트 값을 바꾸기 위해 참조
	WINDOW_ID(SKILL_TRAIN_TITLE),
	WINDOW_ID(SKILL_TRAIN_POINT_TEXT),
	WINDOW_ID(SKILL_TRAIN_POINT_IMAGE),
	WINDOW_ID(SKILL_TRAIN_GUILD_POINT_TEXT),
	WINDOW_ID(SKILL_TRAIN_GUILD_POINT_IMAGE),
	
	WINDOW_ID(STD_SKILLTRAININGBTN),
	WINDOW_ID(STD_SKILLPOINT),

	// desc_hseos_패밀리01
	// S 패밀리 추가 added by hseos 2007.07.02	2007.10.16
	WINDOW_ID(FD_CHANGENICKNAME_BTN),			// 초대신청
	WINDOW_ID(FD_INVITE_BTN),					// 문장등록
	WINDOW_ID(FD_REGISTEMBLEM_BTN),				// 호칭변경
	WINDOW_ID(FD_CHANGENICKNAMEON_BTN),			// 호칭ON
	WINDOW_ID(FD_LEAVE_BTN),					// 탈퇴
	WINDOW_ID(FD_EXPEL_BTN),					// 추방
	WINDOW_ID(FD_BREAKUP_BTN),					// 해체
	WINDOW_ID(FD_FARM_MANAGE_BTN),				// 농장관리
	// E 패밀리 추가 added by hseos 2007.07.02	2007.10.16

	// desc_hseos_농장시스템_01
	// S 농장시스템 추가 added by hseos 2007.08.24	2007.09.10	200.10.23
	WINDOW_ID(FARM_BUY_DLG),
	WINDOW_ID(FARM_BUY_OKBTN),
	WINDOW_ID(FARM_BUY_CANCELBTN),

	WINDOW_ID(FARM_UPGRADE_DLG),
	WINDOW_ID(FARM_UPGRADE_OKBTN),
	WINDOW_ID(FARM_UPGRADE_CANCELBTN),
	WINDOW_ID(FARM_UPGRADE_CUR_GRADE),
	WINDOW_ID(FARM_UPGRADE_NEXT_GRADE),
	WINDOW_ID(FARM_UPGRADE_NEED_GOLD),
	WINDOW_ID(FARM_UPGRADE_NEED_HONOR),

	WINDOW_ID(FARM_MANAGE_DLG),
	WINDOW_ID(FARM_MANAGE_MAPNAME),
	WINDOW_ID(FARM_MANAGE_FARM_NAME),
	WINDOW_ID(FARM_MANAGE_CROP_IMAGE),
	WINDOW_ID(FARM_MANAGE_CROP_NUM),
	WINDOW_ID(FARM_MANAGE_CROP_NAME),
	WINDOW_ID(FARM_MANAGE_CROP_OWNER),
	WINDOW_ID(FARM_MANAGE_CROP_GROW_TIME),
	WINDOW_ID(FARM_MANAGE_CROP_GROW_REMAIN_TIME1),
	WINDOW_ID(FARM_MANAGE_CROP_GROW_REMAIN_TIME2),
	WINDOW_ID(FARM_MANAGE_CROP_GROW_STEP1),
	WINDOW_ID(FARM_MANAGE_CROP_GROW_STEP2),
	WINDOW_ID(FARM_MANAGE_CROP_LIFE),
	WINDOW_ID(FARM_MANAGE_CROP_GROW_REMAIN_TIME_GAUGE),
	WINDOW_ID(FARM_MANAGE_CROP_GROW_STEP_GAUGE),
	WINDOW_ID(FARM_MANAGE_CROP_LIFE_GAUGE),
	WINDOW_ID(FARM_MANAGE_CROP_TAB),
	WINDOW_ID(FARM_MANAGE_ANIMAL_TAB),
	WINDOW_ID(FARM_MANAGE_GARDEN_DLG),
	WINDOW_ID(FARM_MANAGE_GARDEN_CROP01),
	WINDOW_ID(FARM_MANAGE_GARDEN_CROP02),
	WINDOW_ID(FARM_MANAGE_GARDEN_CROP03),
	WINDOW_ID(FARM_MANAGE_GARDEN_CROP04),
	WINDOW_ID(FARM_MANAGE_GARDEN_CROP05),
	WINDOW_ID(FARM_MANAGE_GARDEN_CROP06),
	WINDOW_ID(FARM_MANAGE_GARDEN_CROP07),
	WINDOW_ID(FARM_MANAGE_GARDEN_CROP08),
	WINDOW_ID(FARM_MANAGE_GARDEN_CROP09),
	WINDOW_ID(FARM_MANAGE_GARDEN_CROP10),
	WINDOW_ID(FARM_MANAGE_GARDEN_CROP11),
	WINDOW_ID(FARM_MANAGE_GARDEN_CROP12),
	WINDOW_ID(FARM_MANAGE_GARDEN_CROP13),
	WINDOW_ID(FARM_MANAGE_GARDEN_CROP14),
	WINDOW_ID(FARM_MANAGE_GARDEN_CROP15),
	// E 농장시스템 추가 added by hseos 2007.08.24	2007.09.10	200.10.23

//---KES AUTONOTE
	WINDOW_ID(AND_DLG),
	WINDOW_ID(AND_TEXTAREA_MANUAL),
	WINDOW_ID(AND_BTN_ASK),
	WINDOW_ID(AND_LIST_AUTO),
			
	WINDOW_ID(ASD_DLG),
	WINDOW_ID(ASD_TEXTAREA_DESC),
	WINDOW_ID(ASD_STC_QUESTION),
	WINDOW_ID(ASD_BTN_COLOR1),
	WINDOW_ID(ASD_BTN_COLOR2),
	WINDOW_ID(ASD_BTN_COLOR3),
	WINDOW_ID(ASD_BTN_COLOR4),
	WINDOW_ID(ASD_STC_ANSWER),
	WINDOW_ID(ASD_STC_TIME),
//---------------
//---KES 상점검색
	WINDOW_ID(SSD_DLG),
	WINDOW_ID(SSD_EDITBOX),
	WINDOW_ID(SSD_BTN_OK),
	WINDOW_ID(SSD_BTN_CANCEL),


	// 080313 NYJ --- 전체외치기 다이얼로그
	WINDOW_ID(SHOUT_SHOUTDLG),
	WINDOW_ID(SHOUT_TEXTAREA_MSG),
	WINDOW_ID(SHOUT_BTN_OK),
	WINDOW_ID(SHOUT_BTN_CANCEL),

	// 080414 LUJ, 외양 변경 창
	WINDOW_ID(BODY_CHANGE_DIALOG),
	WINDOW_ID(BODY_CHANGE_HAIR_LEFT),
	WINDOW_ID(BODY_CHANGE_HAIR_RIGHT),
	WINDOW_ID(BODY_CHANGE_FACE_LEFT),
	WINDOW_ID(BODY_CHANGE_FACE_RIGHT),
	WINDOW_ID(BODY_CHANGE_SUBMIT),
	WINDOW_ID(BODY_CHANGE_TITLE_TEXT),
	WINDOW_ID(BODY_CHANGE_HAIR_TEXT),
	WINDOW_ID(BODY_CHANGE_FACE_TEXT),

	// 080421 NYJ --- 낚시 다이얼로그
	WINDOW_ID(FISHING_FISHINGDLG),
	WINDOW_ID(FISHING_BTN_CLOSE),
	WINDOW_ID(FISHING_BTN_START),
	WINDOW_ID(FISHING_ICON_MISSION),
	WINDOW_ID(FISHING_ICON_BAIT),
	WINDOW_ID(FISHING_STATIC_FISHPOINT),
	WINDOW_ID(FISHING_GAUGE_EXP),
	WINDOW_ID(FISHING_STATIC_EXP),
	WINDOW_ID(FISHING_STATIC_PROCESSTIME),

	// 080422 NYJ --- 낚시게이지 다이얼로그
	WINDOW_ID(FISHINGFROGRESSDIALOG),
	WINDOW_ID(FISHINGTIMEGAUGE),
	WINDOW_ID(FISHINGBAR),
	WINDOW_ID(FISHING_STATIC_GRATEZONE),
	WINDOW_ID(FISHING_STATIC_GOODZONE1),
	WINDOW_ID(FISHING_STATIC_GOODZONE2),
	WINDOW_ID(FISHING_STATIC_MISSZONE1),
	WINDOW_ID(FISHING_STATIC_MISSZONE2),

	// 080508 NYJ --- 낚시포인트 다이얼로그
	WINDOW_ID(FISHINGPOINTDLG),
	WINDOW_ID(FISHING_STATIC_ADDFISHPOINT),
	WINDOW_ID(FISHING_STATIC_CURFISHPOINT),
	WINDOW_ID(FISHING_ICON_FISH),
	WINDOW_ID(FISHING_BTN_CHANGEPOINT),
	WINDOW_ID(FISHING_BTN_CLEARSLOT),
	WINDOW_ID(FISHING_BTN_CLOSEPOINT),
	WINDOW_ID(FISHING_BTN_CLOSEPOINTX),

	// 080505 NYJ --- 날씨 다이얼로그
	WINDOW_ID(WEATHERDLG),
	WINDOW_ID(WEATHER_BTN_CLEAR),
	WINDOW_ID(WEATHER_BTN_CLOUDY),
	WINDOW_ID(WEATHER_BTN_RAINY),
	WINDOW_ID(WEATHER_BTN_WINDY),
	WINDOW_ID(WEATHER_BTN_FOGGY),
	WINDOW_ID(WEATHER_BTN_TYPOON),


// 080225 LYW --- WindowIDs : Add window id for chatroom system.
 	// CRMD : Chat Room Main Dialog.
 	WINDOW_ID(CRMD_DLG),
 		WINDOW_ID(CRMD_LST_ROOMLIST),
 
 		WINDOW_ID(CRMD_BTN_SEARCH),
 		WINDOW_ID(CRMD_EDB_SEARCH),
 		WINDOW_ID(CRMD_CMB_ROOMTYPE),
 		WINDOW_ID(CRMD_CHK_TITLE),
 		WINDOW_ID(CRMD_CHK_NAME),
 
 		WINDOW_ID(CRMD_BTN_CREATE),
 		WINDOW_ID(CRMD_BTN_JOIN),
 		WINDOW_ID(CRMD_BTN_NUMJOIN),
 		WINDOW_ID(CRMD_BTN_REFRESH),

		WINDOW_ID(CRMD_BTN_PREV),
  		WINDOW_ID(CRMD_BTN_NEXT),
  
  		WINDOW_ID(CRMD_STC_PAGE),
 
 		WINDOW_ID(CRMD_STC_LOAD_CHATROOM),
 
 	// CRCD : Chat Room Create Dailog.
 	WINDOW_ID(CRCD_DLG),
 		WINDOW_ID(CRCD_CHK_ON),
 		WINDOW_ID(CRCD_CHK_OFF),
 
 		WINDOW_ID(CRCD_EDB_CODE),
 
 		WINDOW_ID(CRCD_CMB_GUEST),
 		WINDOW_ID(CRCD_CMB_ROOMTYPE),
 
 		WINDOW_ID(CRCD_EDB_TITLE),
 
 		WINDOW_ID(CRCD_BTN_OK),
 		WINDOW_ID(CRCD_BTN_CANCEL),
 
 	// CRJD : Chat Room Join Dialog.
 	WINDOW_ID(CRJD_DLG),
 		WINDOW_ID(CRJD_STC_ROOMINDEX),
 		WINDOW_ID(CRJD_STC_CODE),
 		WINDOW_ID(CRJD_STC_INDEX_DESC),
 		WINDOW_ID(CRJD_STC_CODE_DESC),
 		WINDOW_ID(CRJD_EDB_CODE),
 
 		WINDOW_ID(CRJD_BTN_OK),
 		WINDOW_ID(CRJD_BTN_CANCEL),
 
 	// CRD : Chat Room Dialog.
 	WINDOW_ID(CRD_DLG),
		WINDOW_ID(CRD_STC_ROOMTITLE),

 		WINDOW_ID(CRD_LST_CHATLIST),
 
 		WINDOW_ID(CRD_EDB_INPUTBOX),
 
 		WINDOW_ID(CRD_BTN_GUESTLIST),
 		WINDOW_ID(CRD_BTN_OPTION),

		WINDOW_ID(CRD_BTN_CLOSE_DLG),
 
 	// CRGLD : Chat Room Guest List Dialog.
 	WINDOW_ID(CRGLD_DLG),
 		WINDOW_ID(CRGLD_LST_GUESTLIST),
 
 		WINDOW_ID(CRGLD_BTN_CHANGEOWNER),
 		WINDOW_ID(CRGLD_BTN_FREEZEGUEST),
 		WINDOW_ID(CRGLD_BTN_KICKGUEST),
 		WINDOW_ID(CRGLD_BTN_ADDFRIEND),
 
 	// CROD : Chat Room Option Dialog.
 	WINDOW_ID(CROD_DLG),
 		WINDOW_ID(CROD_CHK_ON),
 		WINDOW_ID(CROD_CHK_OFF),
 
 		WINDOW_ID(CROD_EDB_CODE),
 
 		WINDOW_ID(CROD_CMB_GUEST),
 		WINDOW_ID(CROD_CMB_ROOMTYPE),

 		WINDOW_ID(CROD_EDB_TITLE),		
 
 		WINDOW_ID(CROD_BTN_OK),
 		WINDOW_ID(CROD_BTN_CANCEL),	

	// CRLD : Chat Room Lobby Dialog.
	WINDOW_ID(CRLD_DLG), 
		WINDOW_ID(CRLD_LCTR_LOBBY),

		WINDOW_ID(CRLD_BTN_REFRESH),

		WINDOW_ID(CRLD_BTN_PREV),
		WINDOW_ID(CRLD_BTN_NEXT),

		WINDOW_ID(CRLD_STC_PAGE),

		WINDOW_ID(CRLD_STC_LOAD_LOBBY),

	// 080508 KTH --
	WINDOW_ID(FARM_ANIMAL_DLG),
		WINDOW_ID(FARM_ANIMAL_SLOT_NUM),
		WINDOW_ID(FARM_ANIMAL_NAME),
		WINDOW_ID(FARM_ANIMAL_CONTENTMENT_GUAGE),
		WINDOW_ID(FARM_ANIMAL_CONTENTMENT),
		WINDOW_ID(FARM_ANIMAL_HP_GUAGE),
		WINDOW_ID(FARM_ANIMAL_HP),
		WINDOW_ID(FARM_ANIMAL_INTEREST_GUAGE),
		WINDOW_ID(FARM_ANIMAL_INTEREST),
		WINDOW_ID(FARM_ANIMAL_IMAGE),
		WINDOW_ID(FARM_ANIMAL_GET_ITEM_BTN),
		WINDOW_ID(FARM_ANIMAL_CLOSE_BTN),

	WINDOW_ID(PET_INFO_DLG),
	WINDOW_ID(PET_STATUS_BTN),
	WINDOW_ID(PET_INVEN_BTN),
	WINDOW_ID(PET_STATUS_DLG),
	WINDOW_ID(PET_STATUS_NAME),
	WINDOW_ID(PET_STATUS_LEVEL),
	WINDOW_ID(PET_STATUS_TYPE),
	WINDOW_ID(PET_STATUS_FRIENDLY),
	WINDOW_ID(PET_STATUS_GRADE),
	WINDOW_ID(PET_STATUS_AI_COMBOBOX),
	WINDOW_ID(PET_STATUS_AI_COMBOBOX_BTN),
	WINDOW_ID(PET_STATUS_STR),
	WINDOW_ID(PET_STATUS_DEX),
	WINDOW_ID(PET_STATUS_VIT),
	WINDOW_ID(PET_STATUS_INT),
	WINDOW_ID(PET_STATUS_WIS),
	WINDOW_ID(PET_STATUS_PHY_ATT),
	WINDOW_ID(PET_STATUS_PHY_DEF),
	WINDOW_ID(PET_STATUS_ACCURACY),
	WINDOW_ID(PET_STATUS_MAG_ATT),
	WINDOW_ID(PET_STATUS_MAG_DEF),
	WINDOW_ID(PET_STATUS_AVOID),
	WINDOW_ID(PET_STATUS_GRADE_UP),
	WINDOW_ID(PET_INVEN_DLG),
	WINDOW_ID(PET_WEARED_DLG),
	WINDOW_ID(PET_STATUS_GRADE_UP_ACTIVE),
	WINDOW_ID(PET_STATUS_GRADE_UP_INACTIVE),

	WINDOW_ID(PET_UI_DLG),
	WINDOW_ID(PET_UI_LIFE_GUAGE),
	WINDOW_ID(PET_UI_LIFE_STATIC),
	WINDOW_ID(PET_UI_MANA_GUAGE),
	WINDOW_ID(PET_UI_MANA_STATIC),
	WINDOW_ID(PET_UI_EXP_GUAGE),
	WINDOW_ID(PET_UI_EXP_STATIC),
	WINDOW_ID(PET_UI_LEVEL),
	WINDOW_ID(PET_UI_NAME),

	WINDOW_ID(PET_RES_DLG),
	WINDOW_ID(PET_RES_DLG_ICON),
	WINDOW_ID(PET_RES_DLG_OK),
	WINDOW_ID(PET_RES_DLG_CANCEL),

	//---BROWSER
	WINDOW_ID(ISD_DLG),
	WINDOW_ID(ISD_BROWSER),


	/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// 이 아래부터는 id가 틀려지므로 스크립트를 이용한 윈도에서 ID를 구분하려면 이 줄 위로 선언해야 한다.
	//////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////////////////////////
////////////////////
// ¸Þ¼¼Ao¹U½º ¾ÆAIμð
	WINDOW_ID(MAX_SCRIPT_ID),
	WINDOW_ID_DEFINE(MBI_OK,IG_MSGBOX_STRARTINDEX),
	WINDOW_ID(MBI_YES),
	WINDOW_ID(MBI_NO),
	WINDOW_ID(MBI_CANCEL),
//-----------------------------------------------
	WINDOW_ID(MBI_NOBTNMSGBOX),	//-->ⓒoY￥ia¨oA CNⓒoⓒª￠￢￠￢ ¡ic￠?eCIAU. CNE¡ⓒ￠￢e￠?￠® ￠￢i¡Æⓒø ￠Oⓒ￢￠￥A¡ÆI ¨uE￥iE.
	WINDOW_ID(MBI_EXIT),
	// 080121 LYW --- WindowIDs : 캐릭터 선택창으로 이동 확인 메시지 아이디.
	WINDOW_ID(MBI_MOVE_TO_CHARSELECT),
	WINDOW_ID(MBI_PASSERROR),
	WINDOW_ID(MBI_OTHERUSER_CONNECTTRY),
	WINDOW_ID(MBI_DISCONNECTED_OVERLAPPEDLOGIN),
	WINDOW_ID(MBI_SEND_DISCONNECT_OVERLAPPEDLOGIN),
	WINDOW_ID(MBI_VERCHKERROR),
	
	WINDOW_ID(MBI_PARTYBREAKUP),
	
	WINDOW_ID(MBI_STORAGEBUY),

	WINDOW_ID(MBI_SKILLDELETE),
	
	WINDOW_ID(MBI_EXCHANGEAPPLY),
	WINDOW_ID(MBI_EXCHANGEWAITING),
	
	WINDOW_ID(MBI_FRIEND_ADD),
	WINDOW_ID(MBI_PARTY_SECEDE),

	// 070326 LYW --- WindowIDs : Add window id for messagebox of storage part.
	WINDOW_ID(MBI_BUY_COMPLETE), 
	WINDOW_ID(MBI_NOTENOUGH_MONEY), 
	WINDOW_ID(MBI_CANT_CHARGE), 
	WINDOW_ID(MBI_BUY_ALL), 
	WINDOW_ID(MBI_NOTJOIN_GUILD),
	WINDOW_ID(MBI_ITEMSHOP),
	WINDOW_ID(MBI_ITEM_MIX_CONFIRM),
	WINDOW_ID(MBI_ITEM_REINFORCE_CONFIRM),
	
//------------------------------------------------- LBS A¡¤¡Æ￠® 03.09.17
	WINDOW_ID(MBI_MAKESTREETSTALL),
	WINDOW_ID(MBI_BUYREG),

// LBS 03.10.09 ￠￢¨­¨u¨uAo ⓒoU¨o¨￢ ANd￠￢￠c ¨oAAU//////////////////////////////
	WINDOW_ID(MBI_SELECTLOGINPOINT),	// ¡¤I¡¾¡¿AI ¨¡¡AAI¨¡￠c AuAa
	WINDOW_ID(MBI_LOGINEDITCHECK),
	WINDOW_ID(MBI_DELETEICONCHECK),
	WINDOW_ID(MBI_DELETEPETICONCHECK),
	WINDOW_ID(MBI_CHARSELERROR),
	WINDOW_ID(MBI_DELETECHAR),
	WINDOW_ID(MBI_DELETECHARFAIL),
	WINDOW_ID(MBI_CHARMAKEERROR),
	WINDOW_ID(MBI_SHOWDOWNAPPLY),
	WINDOW_ID(MBI_SHOWDOWNWAITING),
	WINDOW_ID(MBI_MAPCHANGE),
	WINDOW_ID(MBI_STREETBUYMSG),
	WINDOW_ID(MBI_STREETSELLMSG),
	WINDOW_ID(MBI_REGEDITMSG),
	WINDOW_ID(MBI_QUESTGIVEUP),
	WINDOW_ID(MBI_BAILNOTICEMSG),
	WINDOW_ID(MBI_BAILNOTICEERR),
	WINDOW_ID(MBI_BAILLOWBADFAME),

	WINDOW_ID(MBI_QUESTSTART),
	WINDOW_ID(MBI_QUEST_NONE),
	WINDOW_ID(MBI_QUEST_DELETE),

	WINDOW_ID(MBI_QUESTQUICKVIEW_FULL), 
	
	WINDOW_ID(MBI_OVERLAPPEDLOGIN),
	WINDOW_ID(MBI_OVERLAPPEDLOGININOTHERSERVER),
	WINDOW_ID(MBI_LOGINERRORCLOSE),
	WINDOW_ID(MBI_LOGINERRORRETURN),
	WINDOW_ID(MBI_MAPSERVER_CLOSE),		
	WINDOW_ID(MBI_SERVERDISCONNECT),	
	WINDOW_ID(MBI_SELLITEM),
	WINDOW_ID(MBI_BUYITEM),				
	WINDOW_ID(MBI_PKMODE),				

	WINDOW_ID(MBI_NOT_GM),				
	WINDOW_ID(MBI_WAIT_LOGINCHECK),
	WINDOW_ID(MBI_TIMEOVER_TOCONNECT),
	WINDOW_ID(MBI_DISTCONNECT_ERROR),	
	WINDOW_ID(MBI_CANTUSEDYNAMIC),		
	WINDOW_ID(MBI_DYNAMICERROR),		

	WINDOW_ID(MBI_MPNOTICE_NOTFIT),		
	WINDOW_ID(MBI_MPNOTICE_SUCCESS),	
	WINDOW_ID(MBI_MPNOTICE_FAIL),		
	
	WINDOW_ID(MBI_GUILD_RETIRE_NOTIFY),
	WINDOW_ID(MBI_GUILD_RETIRE_REQUEST),
	WINDOW_ID(MBI_GUILD_SECEDE),		
	WINDOW_ID(MBI_GUILD_BREAKUP),
	WINDOW_ID(MBI_GUILD_BAN),
	WINDOW_ID(MBI_UNION_DESTROY),	
	WINDOW_ID(MBI_UNION_INVITE),	
	WINDOW_ID(MBI_UNION_REMOVE),
	WINDOW_ID(MBI_UNION_LEAVE),

	WINDOW_ID(MBI_SHOPITEM_LOCK),		// 아이템몰 아이템 봉인해제
	WINDOW_ID(MBI_SAVEDPOINTMOVE),		// 저장포인트로 이동
	WINDOW_ID(MBI_SAVEDPOINTDEL),		// 저장포인트 삭제
	WINDOW_ID(MBI_OTHERREVIVE),			// 부활주문서 사용
	WINDOW_ID(MBI_REVIVECONFIRM),		// 부활할지 확인

	WINDOW_ID(MBI_REVIVE_PRESENTSPOT),	// 재자리 패널티 메시지를 출력하기 위한 아이디
	WINDOW_ID(MBI_REVIVE_TOWNSOPT),		// 안전지대 패널티 메시지를 출력하기 위한 아이디

	WINDOW_ID(MBI_GUILDFIELDWAR_DECLARE_ACCEPT),
	WINDOW_ID(MBI_GUILDFIELDWAR_DECLARE_DENY),
	WINDOW_ID(MBI_GUILDFIELDWAR_CONFIRM),
	WINDOW_ID(MBI_GUILDFIELDWAR_SUGGEST),
	WINDOW_ID(MBI_GUILDFIELDWAR_SURREND),
	WINDOW_ID(MBI_GUILDFIELDWAR_SUGGEST_ACCEPTDENY),
	WINDOW_ID(MBI_GUILDFIELDWAR_REVIVE),	// 길드전 중 사망했을때 부활 처리

	WINDOW_ID(MBI_PARTYWAR_SUGGEST),
/////////////////////////////////////////////////////////////////////

	WINDOW_ID(MBI_SKPOINTREDIST_USE),
	WINDOW_ID(MBI_SKPOINTREDIST_UP),
	WINDOW_ID(MBI_SKPOINTREDIST_DOWN),

	WINDOW_ID(MBI_PRESENT_NOTIFY),

	WINDOW_ID(MBI_SHOUT_ACK),
	WINDOW_ID(MBI_SHOUT_NACK),
	WINDOW_ID(MBI_CHASE_NACK),
	WINDOW_ID(MBI_CHANGENAME_ACK),
	WINDOW_ID(MBI_JOBCHANGE_ACK),

	
	WINDOW_ID(MBI_WANTBUY),
	WINDOW_ID(MBI_WANTGIVEUP),

	// Guild Tournament
	WINDOW_ID(MBI_GTREGIST_SYN),
	WINDOW_ID(MBI_GTREGIST_ACK),
	WINDOW_ID(MBI_GTREGIST_NACK),
	WINDOW_ID(MBI_GTREGISTCANCEL_SYN),
	WINDOW_ID(MBI_GTREGISTCANCEL_ACK),
	WINDOW_ID(MBI_GTREGISTCANCEL_NACK),
	WINDOW_ID(MBI_GTBATTLELIST_OBSERVER),
	WINDOW_ID(MBI_GTSCORE_EXIT),

	///////////////////////////////////////////
	// 06. 06. 2차 전직 - 이영준
	// 무공변환
	WINDOW_ID(MBI_SKILLOPTIONCLEAR_ACK),
	WINDOW_ID(MBI_SKILLOPTIONCLEAR_NACK),
	///////////////////////////////////////////

	WINDOW_ID(MBI_QUESTMSG),

	// 070606 LYW --- WindowIDs : Add window id for matching part.
	WINDOW_ID(MBI_IDENTIFICATION_ERROR),
	WINDOW_ID(MBI_IDENTIFICATION_ALREADY_HAVE), 
	WINDOW_ID(MBI_IDENTIFICATION_REGIST_INFO),

	WINDOW_ID(MBI_MATTINGDLG_ERROR), 

	WINDOW_ID(MBI_MATCHAT_SELECT_PARTNER), 
	WINDOW_ID(MBI_MATCHAT_CANTCHAT), 
	WINDOW_ID(MBI_MATCHAT_READYWAIT), 
	WINDOW_ID(MBI_MATCHAT_TIMEOVER),
	WINDOW_ID(MBI_MATCHAT_NOTICE), 
	WINDOW_ID(MBI_MATCHAT_INVITE), 
	WINDOW_ID(MBI_MATCHAT_ACCEPT), 
	WINDOW_ID(MBI_MATCHAT_REJECT), 
	WINDOW_ID(MBI_MATCHAT_CANCEL), 
	WINDOW_ID(MBI_MATCHAT_STOP), 

	WINDOW_ID(MBI_FRIEND_NOTICE), 
	WINDOW_ID(MBI_FRIEND_INVITEOK), 

	WINDOW_ID(MBI_FRIEND_WAIT), 
	WINDOW_ID(MBI_FRIEND_RECOMMEND), 

	WINDOW_ID(MBI_END_CHATTING_PARTNERLIST), 
	WINDOW_ID(MBI_END_CHATTING_CLOSE), 

	// 070713 LYW --- WindowIDs : Add window id for family dialog part.
	WINDOW_ID(MBI_FAMILY_ERROR_NOTARGET), 

	WINDOW_ID(MBI_FAMILY_CREATE_SUCESS), 
	WINDOW_ID(MBI_FAMILY_ALREADY_HAVE_FAMILY), 
	WINDOW_ID(MBI_FAMILY_SAME_FAMILYNAME), 

	WINDOW_ID(MBI_FAMILY_INVITE), 
	WINDOW_ID(MBI_FAMILY_INVITED), 
	WINDOW_ID(MBI_FAMILY_NO_FAMILY), 
	WINDOW_ID(MBI_FAMILY_ABLE_MASTER), 
	WINDOW_ID(MBI_FAMILY_FULL_MEMBER), 
	WINDOW_ID(MBI_FAMILY_OTHER_FAMILY), 

	WINDOW_ID(MBI_FAMILY_NO_MASTER_POSITION), 
	WINDOW_ID(MBI_FAMILY_INVITE_YOU), 

	WINDOW_ID(MBI_FAMILY_ACCEPT_MASTER), 
	WINDOW_ID(MBI_FAMILY_DENY_MASTER), 
	WINDOW_ID(MBI_FAMILY_ACCEPT_PLAYER), 
	WINDOW_ID(MBI_FAMILY_DENY_PLAYER), 

	WINDOW_ID(MBI_FAMILY_CHANGENAME_COMPLETE), 
	WINDOW_ID(MBI_FAMILY_CHANGENAME_COMPLETE2), 
	WINDOW_ID(MBI_FAMILY_CHANGENAME_FAIL), 

	// desc_hseos_패밀리01
	// S 패밀리 추가 added by hseos 2007.10.16
	WINDOW_ID(MBI_FAMILY_LEAVE), 
	WINDOW_ID(MBI_FAMILY_EXPEL), 
	WINDOW_ID(MBI_FAMILY_BREAKUP), 
	// E 패밀리 추가 added by hseos 2007.10.16

	// 070918 LYW --- WindowIDs : Add message box id.
	WINDOW_ID(MBI_FAILED_NPC_CHANGE_MAP),

	// 071125 LYW --- WindowIDs : 봉인 아이템 관련 알림 메시지 추가.
	WINDOW_ID(MBI_SEALITEM_STREETSTALL), 
	WINDOW_ID(MBI_SEALITEM_EXCHANGE),
	WINDOW_ID(MBI_SEALITEM_STORAGE),
	WINDOW_ID(MBI_SEALITEM_CANTEQUIP),

	// 071130 LYW --- WindowIDs : 맵 이동 주문서의 알림 메시지 아이다.
	WINDOW_ID(MBI_MAPMOVE_AREYOUSURE),
	WINDOW_ID(MBI_MAPMOVE_NOTICE), 

	// 071203 LYW --- WindowIDs : 마나 감소 아이템 재사용 확인 메시지.
	WINDOW_ID(MBI_USEBUFFITEM_AREYOUSURE),
	WINDOW_ID(MBI_FORCE_USEBUFFITEM_AREYOUSURE), 

	// 071204 LYW --- WindowsIDs : 스탯 초기화 아이템 확인 메시지.
	WINDOW_ID(MBI_RESETSTATS_AREYOUSURE), 

	// 071204 LYW --- WindowsIDs : 스킬 초기화 아이템 확인 메시지.
	WINDOW_ID(MBI_RESETSKILL_AREYOUSURE),

	// 080218 KTH -- Reset RegidentRegist
	WINDOW_ID(MBI_RESET_REGIDENTREGIST),

	// 071208 LYW --- WindowsIDs : 맵 이동을 할 수 없는 상태라는 알림 메시지를 위한 메시지 박스 아이디.
	WINDOW_ID(MBI_CANTUSE_MAPMOVESCROLL), 

	// 071205 LYW --- WindowsIDs : 경험치 증가 아이템 확인 메시지.
	WINDOW_ID(MBI_INCEXPRATE_AREYOUSURE), 

	// 071205 LYW --- WindowsIDs : 드랍률 증가 아이템 확인 메시지.
	WINDOW_ID(MBI_INCDROPRATE_AREYOUSURE),

	// 071210 LYW --- WindowsIDs : 인벤토리 확장에 사용하는 메시지.
	WINDOW_ID(MBI_EXTENDINVEN_AREYOUSURE), 

//---KES AUTONOTE
	WINDOW_ID(MBI_AUTONOTEASK),	
//---------------

	// 080414 LUJ, 외양 변경 아이템 사용 확인
	WINDOW_ID(MBI_USEBODYCHANGEITEM),
	
	WINDOW_ID(MBI_PETGRADEUP),


// 080325 LYW --- WindowIDs : Add a window id for messagebox of chatroom system.
 	// ChatRoomCreateDlg part.
 	WINDOW_ID(MBI_CR_SECRETCODE_ERR),
 	WINDOW_ID(MBI_CR_ROOMTITLE_ERR),
	WINDOW_ID(MBI_CR_ENDCHAT),

	WINDOW_ID(MBI_CHATROOM_NOTICE),

//------- DIVIDEBOX￠?￠®¨u¡ⓒ ¡ic￠?e
	WINDOW_ID(DBOX_DIVIDE_INV),
	WINDOW_ID(DBOX_DIVIDE_STREETSTALL),
	WINDOW_ID(DBOX_DIVIDE_STREETBUYSTALL),
	WINDOW_ID(DBOX_SELL),
	WINDOW_ID(DBOX_BUY),
	WINDOW_ID(DBOX_INPUT_MONEY),
	WINDOW_ID(DBOX_EXCHANGE_MONEY),	

// GAMEIN￠?￠®¨u¡ⓒ ¡ic￠?eCI￠￥A Enum ////////////////////////////////////////////////////////////
/*DebugDlg*/		
	WINDOW_ID_DEFINE(DI_DEBUGDLG,IG_DEBUG_START),
	WINDOW_ID(DI_DEBUGCHAT), 
	WINDOW_ID(DI_DEBUGATTACK), 
	WINDOW_ID(DI_DEBUGSKILL), 
	WINDOW_ID(DI_DEBUGMOVE), 
	WINDOW_ID(DI_DEBUGITEM), 
	WINDOW_ID(DI_DEBUGUSERCONN),
////////////////////////////////////////////////////////////////////////////////////////

	// siegewar
	WINDOW_ID(MBI_SW_PROTECTREG_OK),
	WINDOW_ID(MBI_SW_TAXCHANGE_OK),
	WINDOW_ID(MBI_SW_PROFIT_OK),
	WINDOW_ID(MBI_GUILD_CHANGE_LOCATION),

	WINDOW_ID(MBI_SW_ENGRAVE_SYN),
	WINDOW_ID(MBI_SW_PROPOSAL_SYN),
	WINDOW_ID(MBI_SW_ATTACKREGIST_SYN),
	WINDOW_ID(MBI_SW_OBSERVER_SYN),

	 //스크린샷
	WINDOW_ID(SC_STC_TIME), //스태틱(시간)
	WINDOW_ID(SC_MAINDLG), //다이얼로그

	WINDOW_ID(MBI_FAMILY_SECEDE),		//±æμa A≫Að
	WINDOW_ID(MBI_FAMILY_BAN),		//±æμa A|¸i
	WINDOW_ID(MBI_FAMILY_UNION_DESTROY),	
	WINDOW_ID(MBI_FAMILY_UNION_INVITE),	
	WINDOW_ID(MBI_FAMILY_UNION_REMOVE),

	WINDOW_ID(MBI_SKILLTRAIN),
	
	// desc_hseos_결혼_01
	// S 결혼 추가 added by hseos 2007.12.11
	WINDOW_ID(MBI_MARRIAGE_MARRIAGE),
	WINDOW_ID(MBI_MARRIAGE_MARRIAGE_REQUESTED),
	WINDOW_ID(MBI_MARRIAGE_AGREE_DIVORCE),
	WINDOW_ID(MBI_MARRIAGE_AGREE_DIVORCE_REQUESTED),
	WINDOW_ID(MBI_MARRIAGE_FORCE_DIVORCE),
	WINDOW_ID(MBI_MARRIAGE_TELEPORT_TO_PARTNER),
	// E 결혼 추가 added by hseos 2007.12.11

	// desc_hseos_농장시스템_01
	// S 농장시스템 추가 added by hseos 2008.01.17
	WINDOW_ID(MBI_FARM_TAX_PAY_REQUEST),
	WINDOW_ID(MBI_FARM_TAX_PAY_RESULT),
	// E 농장시스템 추가 added by hseos 2008.01.17

	// 080507 KTH --
	WINDOW_ID(MBI_FARM_ANIMAL_INSTALL),

	WINDOW_ID(MAX_IDENUM),				// 여기가 끝이란 의미인듯.? - 2007/03/16 이진영
	//Loading
	WINDOW_ID(LO_02),
	WINDOW_ID(LO_13),
	WINDOW_ID(LO_14),
	WINDOW_ID(LO_15),
	WINDOW_ID(LO_16),
	WINDOW_ID(LO_17),
	WINDOW_ID(LO_19),
	WINDOW_ID(LO_20),
	WINDOW_ID(LO_21),
	WINDOW_ID(LO_22),
	WINDOW_ID(LO_23),
	WINDOW_ID(LO_25),
	WINDOW_ID(LO_26),
	WINDOW_ID(LO_27),
	WINDOW_ID(LO_28),
	WINDOW_ID(LO_29),
	WINDOW_ID(LO_32),
	WINDOW_ID(LO_33),
	WINDOW_ID(LO_34),
	WINDOW_ID(LO_41),
	WINDOW_ID(LO_42),
	WINDOW_ID(LO_51),
	WINDOW_ID(LO_52),
	WINDOW_ID(LO_53),
	WINDOW_ID(LO_54),
	WINDOW_ID(LO_55),
	WINDOW_ID(LO_81),
	WINDOW_ID(LO_82),
	WINDOW_ID(LO_83),
	WINDOW_ID(LO_84),
	WINDOW_ID(LO_91),
	WINDOW_ID(LO_92),
	WINDOW_ID(LO_93),
	WINDOW_ID(LO_94),